### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by R0X4R** [projectdiscovery/nuclei#1025]
**Describe the bug**
I don't know why I am getting this error every time I run nuclei on more than `50urls`. I am getting this error.

**Nuclei version**

```bash
$ nuclei -version

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.5.0

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 2.5.0
```
**Error**

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x7295d5]

goroutine 8235782 [running]:
crypto/tls.(*Conn).write(0xc0117e5180, 0xc015872000, 0x11d, 0x120, 0xc00d373b00, 0x118, 0x180)
        /usr/lib/go-1.13/src/crypto/tls/conn.go:915 +0x135
crypto/tls.(*Conn).writeRecordLocked(0xc0117e5180, 0x16, 0xc00d373b00, 0x118, 0x180, 0x0, 0x0, 0xc00d373b00)
        /usr/lib/go-1.13/src/crypto/tls/conn.go:964 +0x29f
crypto/tls.(*Conn).writeRecord(0xc0117e5180, 0xc00d373b16, 0xc00d373b00, 0x118, 0x180, 0x0, 0x0, 0x0)
        /usr/lib/go-1.13/src/crypto/tls/conn.go:986 +0xe2
crypto/tls.(*Conn).clientHandshake(0xc0117e5180, 0x0, 0x0)
        /usr/lib/go-1.13/src/crypto/tls/handshake_client.go:167 +0x179
crypto/tls.(*Conn).Handshake(0xc0117e5180, 0x0, 0x0)
        /usr/lib/go-1.13/src/crypto/tls/conn.go:1362 +0x12b
net/http.(*persistConn).addTLS.func2(0x0, 0xc0117e5180, 0x0, 0xc00338b6e0)
        /usr/lib/go-1.13/src/net/http/transport.go:1414 +0x42
created by net/http.(*persistConn).addTLS
        /usr/lib/go-1.13/src/net/http/transport.go:1410 +0x1aa
```

**Comment by ehsandeep** [comment]
@R0X4R thanks for reporting, we are tracking this issue here - https://github.com/projectdiscovery/nuclei/issues/998
