### ISSUE TITLE
-project option is causing nuclei to crash

### ISSUE THREAD

**Issue by Pheelbert** [projectdiscovery/nuclei#1252]
The -project argument is causing a crash. I tried supplying a different directory too using -project-path.

### Nuclei version:
2.5.3

### Current Behavior:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xcbb114]

goroutine 25461 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc001b60160, {0xc0007ba320, 0x1c}, 0xc003bf1d10, 0x0, 0x0, 0xc0053b3d98, 0xc00093b000)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/http/request.go:389 +0x10f4
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc001b60160, {0xc0007ba320, 0x1c}, 0xc003bf1b30, 0x59, 0xc003bf1b90)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/http/request.go:240 +0x3f3
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc001b29400, {0xc0007ba320, 0x1c})
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/common/executer/executer.go:52 +0x18e
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1.1({0xc0007ba320, 0xffffffffffffffff})
        /home/runner/work/nuclei/nuclei/v2/internal/runner/processor.go:34 +0xa7
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1
        /home/runner/work/nuclei/nuclei/v2/internal/runner/processor.go:31 +0x17d
```

### Steps To Reproduce:
```
nuclei -u https://www.example.com -project
```

**Comment by LuitelSamikshya** [comment]
The issue seems to be in the master branch, the fix for this is https://github.com/projectdiscovery/nuclei/pull/1184 and already merged to the dev branch.
