### ISSUE TITLE
Nuclei throws a SIGSEV when data is piped into it

### ISSUE THREAD

**Issue by 0x0luke** [projectdiscovery/nuclei#1328]
### Nuclei version:
2.5.3

### Current Behavior:
Nuclei throws a SIGSEV when attempting to launch a scan, Tried on both Ubuntu 20.04 Server and ParrotOS Security. Same error is thrown each time. I've downgraded to 2.5.2 and the error doesn't occur anymore.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xcc07b4]

goroutine 101 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc001eaa420, {0xc0003183c0, 0x14}, 0xc002126cf0, 0x0, 0x0, 0xc003861d98, 0x6863202d20202020)
        /home/luke/.go/bin/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/http/request.go:389 +0x10f4
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc001eaa420, {0xc0003183c0, 0x14}, 0xc002126a80, 0x732d72656d6f7473, 0xc002126b10)
        /home/luke/.go/bin/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/http/request.go:240 +0x3f3
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc001f0a5c0, {0xc0003183c0, 0x14})
        /home/luke/.go/bin/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/pkg/protocols/common/executer/executer.go:52 +0x18e
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1.1({0xc0003183c0, 0x622d6967632f202d})
        /home/luke/.go/bin/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/internal/runner/processor.go:34 +0xa7
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1
        /home/luke/.go/bin/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.5.3/internal/runner/processor.go:31 +0x17d
```

### Expected Behavior:
Nuclei runs.

### Steps To Reproduce:
I'm using the following command to execute nuclei. The data is piped in via a bash pipe.

` nuclei -t $HOME/nuclei-templates -severity critical,high -retries 1 -timeout 3 -o nuclei/$n.txt -project -project-path nuclei/project -silent;`

### Anything else:
The domain list i'm using is just output from httprobe, so they're formatted as so.

```
http://sub.domain.com
https://sub.domain.com
```

**Comment by Remourz** [comment]
got the same issue

**Comment by ehsandeep** [comment]
@0x0luke @Remourz this is already fixed in the dev branch - https://github.com/projectdiscovery/nuclei/issues/1252

**Comment by Remourz** [comment]
I've cloned the master into my linux how do i delete all of it and clone the dev?
