### ISSUE TITLE
Docker nuclei  invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by wellencamass** [projectdiscovery/nuclei#1759]
Hello, I've got SIGSEGV on ubuntu 20, latest docker projectdiscovery/nuclei image run by:

```
docker run --rm --cpu-shares 256 --network=docker_default -v nuclei:/nuclei -v configs:/root/ projectdiscovery/nuclei -t /root/nuclei-templates/ -list list.txt -stats -o out.json -json -irr -retries 3 -max-host-error 5000 -timeout 25 -rl 1 -bs 500 -c 5
```

Nuclei container stopped its work and thats all i've got:

Whole error message:
```console
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "panic: runtime error: invalid memory address or nil pointer dereference"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x609b5f]"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "goroutine 458324 [running]:"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "crypto/tls.(*Conn).write(0xc006c07c00, {0xc0083ae000, 0x5, 0xc005132900})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:912 +0xff"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "crypto/tls.(*Conn).writeRecordLocked(0xc006c07c00, 0x16, {0xc00bc50d80, 0x108, 0x180})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:980 +0x351"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "crypto/tls.(*Conn).writeRecord(0xc005be9000, 0x60, {0xc00bc50d80, 0xc00322a360, 0x0})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1002 +0xe5"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "crypto/tls.(*Conn).clientHandshake(0xc006c07c00, {0x19d6d98, 0xc0051c0300})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/usr/local/go/src/crypto/tls/handshake_client.go:175 +0x205"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "crypto/tls.(*Conn).handshakeContext(0xc006c07c00, {0x19d6dd0, 0xc00003a030})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1445 +0x3d1"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "crypto/tls.(*Conn).HandshakeContext(...)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1395"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "crypto/tls.(*Conn).Handshake(...)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1379"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/rawhttp.TlsHandshake({0x0, 0x0}, {0xc00d1e18d8, 0x40edd4})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:112 +0x165"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/rawhttp.clientDial({0x13e2845, 0x5}, {0xc00d1e18d8, 0x15}, 0x18)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:93 +0x6a"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/rawhttp.(*dialer).dialTimeout(0xc001dc3e80, {0x13e2845, 0x5}, {0xc00d1e18d8, 0x15}, 0x7fba7dbd4108)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:53 +0x1d7"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/rawhttp.(*dialer).DialTimeout(0x5f0000c00304db50, {0x13e2845, 0x2}, {0xc00d1e18d8, 0xc002580628}, 0x11)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:36 +0x25"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).getConn(0x203001, {0x13e2845, 0x48814f}, {0xc00d1e18d8, 0x19dd078}, {0xdf8475800, 0x0, 0xa, 0x1, 0x1, ...})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:102 +0x52"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).do(0xc000680000, {0xc00dabb440, 0x3}, {0xc002580620, 0xc00bf77360}, {0xc00dabb444, 0xc00bf77360}, 0xc007b96000, {0x7fba560dc478, 0xc00304db30}, ...)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:150 +0x4ae"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).DoRawWithOptions(0x7fba560c1700, {0xc00dabb440, 0x5e0d6e}, {0xc002580620, 0x7fba561c0570}, {0xc00dabb444, 0x1}, 0xc00bf774a0, {0x7fba560dc478, 0xc00304db30}, ...)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:92 +0xcd"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc003d40b00, {0xc002580620, 0x19}, 0xc004751770, 0x7fba56890618, 0x0, 0xc005133c70, 0x40edd4)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:387 +0xb58"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc0017127d0, 0x41}, 0x203000, 0xc0031faed0)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:262 +0x3ac"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc003d40b00, {0xc002580620, 0x19}, 0xc0031fade0, 0xc0031faea0, 0xc0031faed0)"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:315 +0x289"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc003d3fa00, {0xc002580620, 0x19})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/common/executer/executer.go:68 +0x1ae"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0, 0x0, {0xc002580620, 0x0})"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/core/execute.go:142 +0x12b"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2"
[24-Mar-2022 01:39:54] WARNING: [pool www] child 33845 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/core/execute.go:129 +0x6d0"
```

**Comment by ehsandeep** [comment]
@wellencamass it was something that got fixed in a release published 3 days ago, can you confirm the version of nuclei running with docker?

**Comment by wellencamass** [comment]
Hello, @ehsandeep 

Its latest

projectdiscovery/nuclei   latest    178066cccf3b   2 days ago      365MB

```
docker pull projectdiscovery/nuclei
Using default tag: latest
latest: Pulling from projectdiscovery/nuclei
Digest: sha256:3f853a46d22485fdd36994ac48f91065faa47bba227fc4358ecbadb1df1a8ecd
Status: Image is up to date for projectdiscovery/nuclei:latest
docker.io/projectdiscovery/nuclei:latest
```

**Comment by wellencamass** [comment]
Nope, latest version from dockerhub.
When mem is not enough and swap starts being used after some time this happens

```
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "panic: runtime error: invalid memory address or nil pointer dereference"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x609b5f]"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "goroutine 614252 [running]:"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "crypto/tls.(*Conn).write(0xc0086fe700, {0xc00a20b400, 0x5, 0xc001a0e900})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:912 +0xff"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "crypto/tls.(*Conn).writeRecordLocked(0xc0086fe700, 0x16, {0xc0048c9200, 0x107, 0x180})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:980 +0x351"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "crypto/tls.(*Conn).writeRecord(0xc006f5fc00, 0x0, {0xc0048c9200, 0xc004f3d500, 0x0})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1002 +0xe5"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "crypto/tls.(*Conn).clientHandshake(0xc0086fe700, {0x19d6d98, 0xc00303a000})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/usr/local/go/src/crypto/tls/handshake_client.go:175 +0x205"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "crypto/tls.(*Conn).handshakeContext(0xc0086fe700, {0x19d6dd0, 0xc00003a030})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1445 +0x3d1"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "crypto/tls.(*Conn).HandshakeContext(...)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1395"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "crypto/tls.(*Conn).Handshake(...)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/usr/local/go/src/crypto/tls/conn.go:1379"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/rawhttp.TlsHandshake({0x0, 0x0}, {0xc00382ed38, 0x40edd4})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:112 +0x165"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/rawhttp.clientDial({0x13e2845, 0x5}, {0xc00382ed38, 0x14}, 0x18)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:93 +0x6a"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/rawhttp.(*dialer).dialTimeout(0xc001a26740, {0x13e2845, 0x5}, {0xc00382ed38, 0x14}, 0x7f46e23b31d8)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:53 +0x1d7"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/rawhttp.(*dialer).DialTimeout(0x6d0000c00268e490, {0x13e2845, 0x2}, {0xc00382ed38, 0xc007fac9c8}, 0x10)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:36 +0x25"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).getConn(0x203000, {0x13e2845, 0x48814f}, {0xc00382ed38, 0x19dd078}, {0xdf8475800, 0x0, 0xa, 0x1, 0x1, ...})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:102 +0x52"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).do(0xc009692000, {0xc008b6ef00, 0x3}, {0xc007fac9c0, 0xc009269360}, {0xc008b6ef04, 0xc009269360}, 0xc00a619b90, {0x7f46bb020f90, 0xc00268e2e0}, ...)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:150 +0x4ae"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).DoRawWithOptions(0x7f46bb90f200, {0xc008b6ef00, 0x5e0d6e}, {0xc007fac9c0, 0x7f46bb215368}, {0xc008b6ef04, 0x1}, 0xc0092694a0, {0x7f46bb020f90, 0xc00268e2e0}, ...)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:92 +0xcd"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc00528e420, {0xc007fac9c0, 0x18}, 0xc006120a00, 0xd80000c005365570, 0x0, 0xc001a0fc70, 0xc0007b9c10)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:387 +0xb58"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc003ac9680, 0x2d}, 0x203002, 0xc00a6198c0)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:262 +0x3ac"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc00528e420, {0xc007fac9c0, 0x18}, 0xc00a619860, 0xc00a619890, 0xc00a6198c0)"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:315 +0x289"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc00127c240, {0xc007fac9c0, 0x18})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/common/executer/executer.go:68 +0x1ae"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0, 0x0, {0xc007fac9c0, 0x0})"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/core/execute.go:142 +0x12b"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2"
[25-Mar-2022 13:35:09] WARNING: [pool www] child 11396 said into stderr: "	/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/core/execute.go:129 +0x6d0"
```

**Comment by wellencamass** [comment]
Same on the mac os:
```

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "panic: runtime error: invalid memory address or nil pointer dereference"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x609b5f]"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "goroutine 2262531 [running]:"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "crypto/tls.(*Conn).write(0xc00ccd7c00, {0xc015134500, 0x5, 0xc002b86900})"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /usr/local/go/src/crypto/tls/conn.go:912 +0xff"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "crypto/tls.(*Conn).writeRecordLocked(0xc00ccd7c00, 0x16, {0xc009dce180, 0x115, 0x180})"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /usr/local/go/src/crypto/tls/conn.go:980 +0x351"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "crypto/tls.(*Conn).writeRecord(0xc009ab0400, 0x4d, {0xc009dce180, 0x1e, 0x0})"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /usr/local/go/src/crypto/tls/conn.go:1002 +0xe5"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "crypto/tls.(*Conn).clientHandshake(0xc00ccd7c00, {0x19d6d98, 0xc001260840})"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /usr/local/go/src/crypto/tls/handshake_client.go:175 +0x205"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "crypto/tls.(*Conn).handshakeContext(0xc00ccd7c00, {0x19d6dd0, 0xc00003a020})"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /usr/local/go/src/crypto/tls/conn.go:1445 +0x3d1"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "crypto/tls.(*Conn).HandshakeContext(...)"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /usr/local/go/src/crypto/tls/conn.go:1395"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "crypto/tls.(*Conn).Handshake(...)"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /usr/local/go/src/crypto/tls/conn.go:1379"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/rawhttp.TlsHandshake({0x0, 0x0}, {0xc005f83440, 0x40edd4})"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:112 +0x165"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/rawhttp.clientDial({0x13e2845, 0x5}, {0xc005f83440, 0x22}, 0x30)"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:93 +0x6a"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/rawhttp.(*dialer).dialTimeout(0xc001c95a30, {0x13e2845, 0x5}, {0xc005f83440, 0x22}, 0x7f27df9ec108)"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:53 +0x1d7"

[01-Apr-2022 20:16:12] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/rawhttp.(*dialer).DialTimeout(0x380000c00670ac40, {0x13e2845, 0x2}, {0xc005f83440, 0xc009b1d1d8}, 0x1e)"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/conn.go:36 +0x25"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).getConn(0x203003, {0x13e2845, 0x48814f}, {0xc005f83440, 0x19dd078}, {0xdf8475800, 0x0, 0xa, 0x1, 0x1, ...})"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:102 +0x52"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).do(0xc00b0aa400, {0xc0011af360, 0x3}, {0xc009b1d1d0, 0xc00f5ab360}, {0xc0011af364, 0xc00f5ab360}, 0xc01679a780, {0x7f27b8969718, 0xc00670ac20}, ...)"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:150 +0x4ae"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/rawhttp.(*Client).DoRawWithOptions(0xc00f5ab448, {0xc0011af360, 0x5e0d6e}, {0xc009b1d1d0, 0x0}, {0xc0011af364, 0xc005540680}, 0xc00f5ab448, {0x7f27b8969718, 0xc00670ac20}, ...)"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/rawhttp@v0.0.8/client.go:92 +0xcd"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc002bb5ce0, {0xc009b1d1d0, 0x26}, 0xc00919def0, 0x7f27b89854a8, 0x0, 0xc002b87c70, 0x40edd4)"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:387 +0xb58"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc004844ea0, 0x5f}, 0x203007, 0xc01d58ac30)"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:262 +0x3ac"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc002bb5ce0, {0xc009b1d1d0, 0x26}, 0xc01d58abd0, 0xc01d58ac00, 0xc01d58ac30)"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/http/request.go:315 +0x289"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc00117bd40, {0xc009b1d1d0, 0x26})"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/protocols/common/executer/executer.go:68 +0x1ae"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x6f694768, 0x4b, {0xc009b1d1d0, 0x464a61314c475235})"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/core/execute.go:142 +0x12b"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: "created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2"

[01-Apr-2022 20:16:13] WARNING: [pool www] child 39455 said into stderr: " /go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.6.4/pkg/core/execute.go:129 +0x6d0"
```

**Comment by ehsandeep** [comment]
@wellencamass it was an issue with the docker image update as a result, the older version of nuclei was pushed as the latest version to dockerhub which is now fixed, so if you try to pull the latest version, this error should be also fixed.

**Comment by wellencamass** [comment]
thanks, @ehsandeep!
