### ISSUE TITLE
Nuclei crashing everytime 

### ISSUE THREAD

**Issue by jakre1234** [projectdiscovery/nuclei#1792]
Hey I have been facing issues with nuclei lately, it's crashing again and again when combined with httpx. Below is the error generated

```console
panic: interface conversion: interface {} is float64, not int

goroutine 31236 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/operators/common/dsl.HelperFunctions.func29(0xc003952f30, 0x1, 0x1, 0x0, 0xc0000100e8, 0x8, 0x8)
        /home/runner/work/nuclei/nuclei/v2/pkg/operators/common/dsl/dsl.go:196 +0x18b
github.com/Knetic/govaluate.makeFunctionStage.func1(0x0, 0x0, 0xdf4500, 0xc00275ea88, 0x12c1200, 0xc003952f20, 0x0, 0x0, 0xc, 0xc002781810)
        /home/runner/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/evaluationStage.go:244 +0x104
github.com/Knetic/govaluate.EvaluableExpression.evaluateStage(0x10489eb, 0x22, 0x1, 0xc001b72c60, 0x4, 0x4, 0xc002781860, 0xc0025bf124, 0xc, 0xc002781860, ...)
        /home/runner/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:228 +0x174
github.com/Knetic/govaluate.EvaluableExpression.Eval(0x10489eb, 0x22, 0x1, 0xc001b72c60, 0x4, 0x4, 0xc002781860, 0xc0025bf124, 0xc, 0x12c3240, ...)
        /home/runner/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:159 +0xb3
github.com/Knetic/govaluate.EvaluableExpression.Evaluate(0x10489eb, 0x22, 0x1, 0xc001b72c60, 0x4, 0x4, 0xc002781860, 0xc0025bf124, 0xc, 0xc003a9fb30, ...)
        /home/runner/go/pkg/mod/github.com/!knetic/govaluate@v3.0.0+incompatible/EvaluableExpression.go:136 +0x88
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/expressions.Evaluate(0xc0025bf0a0, 0xd1, 0xc003a9fb30, 0xc003db93b0, 0x3, 0x0, 0x0)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/common/expressions/expressions.go:31 +0x329
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).handleRawWithPayloads(0xc001bb13a0, 0x12d2b40, 0xc00011a568, 0xc00151a1a0, 0xc4, 0xc003db93b0, 0x21, 0xc003a9fb00, 0x0, 0xe00800, ...)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/http/build_request.go:134 +0x6e
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).makeHTTPRequestFromRaw(0xc001bb13a0, 0x12d2b40, 0xc00011a568, 0xc003db93b0, 0x21, 0xc00151a1a0, 0xc4, 0xc003a9fb00, 0x0, 0x0, ...)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/http/build_request.go:123 +0xa5
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*requestGenerator).Make(0xc001bb13a0, 0xc0025df920, 0x21, 0xc003a9f9b0, 0x0, 0x0, 0xf69d00, 0x30, 0x7f4ffe75f108)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/http/build_request.go:68 +0x3d5
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc00150ab00, 0xc0025df920, 0x21, 0xc003a9f9b0, 0xc003a9f9e0, 0xc003a9fad0, 0x203000, 0x203000)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/http/request.go:207 +0x145
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc000c063c0, 0xc0025df920, 0x21, 0x30, 0xf69c20, 0xe31e01)
        /home/runner/work/nuclei/nuclei/v2/pkg/protocols/common/executer/executer.go:53 +0x15e
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1.1(0xc001ebee20, 0xc000fcdba0, 0xc0006be000, 0xc001e638f8, 0xc0025df920, 0x21)
        /home/runner/work/nuclei/nuclei/v2/internal/runner/processor.go:21 +0x9d
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1
        /home/runner/work/nuclei/nuclei/v2/internal/runner/processor.go:18 +0xfb
```

**Comment by ehsandeep** [comment]
@jakre1234 Could you also provide the version of nuclei in use and sample input to replicate this?

**Comment by mikicaivosevic** [comment]
I have the same problem with `v2.3.4` and `nuclei-templates v8.9.3` and it's only when I use `-t cves`. 

sample input: `nuclei -u "https://projectdiscovery.io" -t cves/`

**Comment by ehsandeep** [comment]
> I have the same problem with `v2.3.4` and `nuclei-templates v8.9.3` and it's only when I use `-t cves`.
> 
> sample input: `nuclei -u "https://projectdiscovery.io" -t cves/`

Yes, the issue here is the use of an outdated version of nuclei engine with the latest version of templates, simply updating nuclei to the latest version i.e [v2.6.5](https://github.com/projectdiscovery/nuclei/releases/tag/v2.6.5) will resolve the issue.

**Comment by mikicaivosevic** [comment]
> > I have the same problem with `v2.3.4` and `nuclei-templates v8.9.3` and it's only when I use `-t cves`.
> > sample input: `nuclei -u "https://projectdiscovery.io" -t cves/`
> 
> Yes, the issue here is the use of an outdated version of nuclei engine with the latest version of templates, simply updating nuclei to the latest version i.e [v2.6.5](https://github.com/projectdiscovery/nuclei/releases/tag/v2.6.5) will resolve the issue.

Tnx, that was the problem :)

**Comment by ehsandeep** [comment]
closing since this is fixed already in latest version.
