### ISSUE TITLE
SIGSEGV when running nuclei as user nobody

### ISSUE THREAD

**Issue by hkoosha** [projectdiscovery/nuclei#2217]
### health-check

```
nuclei -health-check

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
Version: 2.7.3
Operative System: linux
Architecture: amd64
Go Version: go1.18.3
Compiler: gc
File "/.config/nuclei/config.yaml" Read => Ko (open /.config/nuclei/config.yaml: no such file or directory)
File "/.config/nuclei/config.yaml" Write => Ko (open /.config/nuclei/config.yaml: no such file or directory)
File "/.config/nuclei/.nuclei-ignore" Read => Ko (open /.config/nuclei/.nuclei-ignore: no such file or directory)
File "/.config/nuclei/.nuclei-ignore" Write => Ko (open /.config/nuclei/.nuclei-ignore: no such file or directory)
File "/nuclei-templates/.checksum" Read => Ko (open /nuclei-templates/.checksum: no such file or directory)
File "/nuclei-templates/.checksum" Write => Ko (open /nuclei-templates/.checksum: no such file or directory)
IPv4 connectivity to scanme.sh:80 => Ok
IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: network is unreachable)
IPv4 UDP connectivity to scanme.sh:53 => Ok
```

### Current Behavior:

When running nuclei as user `nobody`, it ends up with a SIGSEGV:

```
$> uname -a
Linux **** 5.4.170+ #1 SMP **** x86_64 Linux

$> whoami
nobody

$> nuclei
                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[ERR] Could not update templates: could not write template configuration: open /.config/nuclei/.templates-config.json: no such file or directory
[ERR] Could not read nuclei-ignore file: open /.config/nuclei/.nuclei-ignore: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10aa8f5]

goroutine 1 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/catalog/loader.NewConfig(...)
	github.com/projectdiscovery/nuclei/v2/pkg/catalog/loader/loader.go:79
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration(0xc000331ea0)
	github.com/projectdiscovery/nuclei/v2/internal/runner/runner.go:346 +0xa75
main.main()
	./main.go:69 +0x42f
```

### Expected Behavior:
I expect nuclei to run as usual under the user nobody, without throwing SIGSEGV or if it needs to access a resource which is not available/accessible, nuclei should print a meaningful message about it.

In other words nuclei should handle inaccessible resources as an expected situation, printing meaningful errors and aborting process itself, instead of OS killing the process with SIGSEGV.

### Steps To Reproduce:
1. Switch to user nobody or build a docker image running as user nobody (doesn't make a difference).
2. Run nuclei, with or without any flags.
3. SIGSEGV.

**Comment by hkoosha** [comment]
Sure!

```
nuclei -health-check

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
Version: 2.7.3
Operative System: linux
Architecture: amd64
Go Version: go1.18.3
Compiler: gc
File "/.config/nuclei/config.yaml" Read => Ko (open /.config/nuclei/config.yaml: no such file or directory)
File "/.config/nuclei/config.yaml" Write => Ko (open /.config/nuclei/config.yaml: no such file or directory)
File "/.config/nuclei/.nuclei-ignore" Read => Ko (open /.config/nuclei/.nuclei-ignore: no such file or directory)
File "/.config/nuclei/.nuclei-ignore" Write => Ko (open /.config/nuclei/.nuclei-ignore: no such file or directory)
File "/nuclei-templates/.checksum" Read => Ko (open /nuclei-templates/.checksum: no such file or directory)
File "/nuclei-templates/.checksum" Write => Ko (open /nuclei-templates/.checksum: no such file or directory)
IPv4 connectivity to scanme.sh:80 => Ok
IPv6 connectivity to scanme.sh:80 => Ko (dial tcp6 [2400:6180:0:d0::91:1001]:80: connect: network is unreachable)
IPv4 UDP connectivity to scanme.sh:53 => Ok
```
