### ISSUE TITLE
IO wait crash

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/nuclei#2286]
```
goroutine 728678 [IO wait]:
internal/poll.runtime_pollWait(0x9fc0058, 0x72)
	/usr/local/Cellar/go/1.18.4/libexec/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc000329e00?, 0xc018da9000?, 0x0)
	/usr/local/Cellar/go/1.18.4/libexec/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.18.4/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc000329e00, {0xc018da9000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18.4/libexec/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000329e00, {0xc018da9000?, 0x1?, 0xc014014015?})
	/usr/local/Cellar/go/1.18.4/libexec/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc007746818, {0xc018da9000?, 0xc007252cc0?, 0xc014014015?})
	/usr/local/Cellar/go/1.18.4/libexec/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc0004cfb00, {0xc018da9000?, 0x400a93d?, 0x60?})
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc00b46aae0)
	/usr/local/Cellar/go/1.18.4/libexec/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc00b46aae0, 0x1)
	/usr/local/Cellar/go/1.18.4/libexec/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc0004cfb00)
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/transport.go:1750 +0x173e

goroutine 723798 [select]:
net/http.(*persistConn).roundTrip(0xc00aff8ea0, 0xc009bade00)
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/transport.go:2620 +0x974
net/http.(*Transport).roundTrip(0xc0083e7900, 0xc01b23d600)
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/transport.go:594 +0x7c9
net/http.(*Transport).RoundTrip(0xc01b23d600?, 0x6e98bc0?)
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc00a3ab600, {0x6e98bc0, 0xc0083e7900}, {0x59a75e0?, 0x4091c01?, 0x82732e0?})
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0089c0db0, 0xc00a3ab600, {0x4392065?, 0xc01d18c210?, 0x82732e0?})
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0089c0db0, 0xc00a3ab600)
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
	/usr/local/Cellar/go/1.18.4/libexec/src/net/http/client.go:593
github.com/projectdiscovery/retryablehttp-go.(*Client).Do(0xc0083ee460, 0xc00c8573e0)
	/Users/51pwn/MyWork/scan4all/vendor/github.com/projectdiscovery/retryablehttp-go/do.go:64 +0x34b
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc0139da900, {0xc006c9f580, 0x19}, 0xc01b507f90, 0xc0089d33c0?, 0x0, 0xc006b2da00, 0x5a18c6a?)
	/Users/51pwn/MyWork/scan4all/vendor/github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:425 +0xd25
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc01383ef00, 0x12}, 0x0, 0xc00c857170)
	/Users/51pwn/MyWork/scan4all/vendor/github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:270 +0x58b
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc0139da900, {0xc006c9f580, 0x19}, 0xc00c857170, 0xc00c8571a0, 0xc00c8571d0)
	/Users/51pwn/MyWork/scan4all/vendor/github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:322 +0x275
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc0139f4420, {0xc006c9f580, 0x19})
	/Users/51pwn/MyWork/scan4all/vendor/github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x6d127d0?, 0xc0?, {0xc006c9f580?, 0xc009ce9e60?})
	/Users/51pwn/MyWork/scan4all/vendor/github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:142 +0x11e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
	/Users/51pwn/MyWork/scan4all/vendor/github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:129 +0x6ad
```

**Comment by Mzack9999** [comment]
@hktalent Can you provide more information about how to reproduce the issue (command, snippet, etc) and the execution environment? That's very hard otherwise for us to provide proper help. Thanks!

**Comment by hktalent** [comment]
> @hktalent Can you provide more information about how to reproduce the issue (command, snippet, etc) and about the execution environment? That's very hard otherwise for us to provide proper help. Thanks!

@Mzack9999  my code here
```
https://github.com/hktalent/scan4all/blob/main/nuclei_Yaml/nuclei_yaml.go
```
cmd

**Comment by wh1ter0ze** [comment]
I have the same problem how to fix it?

**Comment by xm1k3** [comment]
> @Mzack9999 my code here
> https://github.com/hktalent/scan4all/blob/main/nuclei_Yaml/nuclei_yaml.go
> But what I'm sure about is that the http yaml detection is performed because many targets in the incoming list are not http, for example:
> 1. This is actually the ssh service
> http://127.0.0.1:22/
> 2. this is actually a mysql service
> http://127.0.0.1:3306/

Hey @hktalent 

seems like this URL is not valid anymore:
```
https://github.com/hktalent/scan4all/blob/main/nuclei_Yaml/nuclei_yaml.go
```
Do you have another link to share?
