### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by Sahabalam** [projectdiscovery/nuclei#2333]
Running : Nuclei high                                             

panic: runtime error: integer divide by zero

goroutine 10640 [running]:
github.com/projectdiscovery/retryabledns.(*Client).Do(0xc00067b380, 0x1?)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/retryabledns@v1.0.13/client.go:109 +0x32e
github.com/projectdiscovery/nuclei/v2/pkg/protocols/dns.(*Request).ExecuteWithResults(0xc004524b40, {0xc0073175f0, 0x2b}, 0xc004cce7b0?, 0xc004cce7e0?, 0xc004cce810)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.4/pkg/protocols/dns/request.go:83 +0x725
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc005393860, {0xc0073175f0, 0x2b})
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.4/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0?, 0x0?, {0xc0073175f0?, 0xffffffffffffffff?})
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.4/pkg/core/execute.go:142 +0x11e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.4/pkg/core/execute.go:129 +0x6ad

**Comment by gy741** [comment]
Hello,

Can you provide files that cause conflicts?

**Comment by ehsandeep** [comment]
@Sahabalam please include **cmd/data** to replicate this crash.
