### ISSUE TITLE
An error occurred during the scan

### ISSUE THREAD

**Issue by Ma1Dong** [projectdiscovery/nuclei#2449]
### Anything else:

scan with the problem
![图片](https://user-images.githubusercontent.com/52943794/185143810-ad2703ed-907f-4579-9e04-a7eb894907c7.png)

Partial Log Information：
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:437 +0xd85
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc00835f5f0, 0x2b}, 0x0, 0xc00705a000)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:282 +0x79a
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc00837aea0, {0xc0033f0ac0, 0x20}, 0xc00705a000, 0xc00705a030, 0xc00705a060)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:334 +0x36d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc007f68a00, {0xc0033f0ac0, 0x20})
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x108cdca?, 0x0?, {0xc0033f0ac0?, 0xc005887080?})
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:142 +0x11e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:129 +0x6ae

goroutine 814317 [select]:
net/http.(*Transport).getConn(0xc0000a5040, 0xc00205e400, {{}, 0x0, {0xc00e397920, 0x5}, {0xc009914f00, 0x12}, 0x0})
        net/http/transport.go:1375 +0x5c6
net/http.(*Transport).roundTrip(0xc0000a5040, 0xc00c605d00)
        net/http/transport.go:581 +0x76f
net/http.(*Transport).RoundTrip(0xc00c605d00?, 0x2420da0?)
        net/http/roundtrip.go:17 +0x19
net/http.send(0xc00ecdf300, {0x2420da0, 0xc0000a5040}, {0x1da0f00?, 0xe54801?, 0x2dc55c0?})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00091b3e0, 0xc00ecdf300, {0x50?, 0x17ee5d134a0?, 0x2dc55c0?})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00091b3e0, 0xc00ecdf300)
        net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/projectdiscovery/retryablehttp-go.(*Client).Do(0xc0002f43f0, 0xc002cb6bd0)
        github.com/projectdiscovery/retryablehttp-go@v1.0.3-0.20220506110515-811d938bd26d/do.go:64 +0x34b
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc0078249c0, {0xc0111566d8, 0x16}, 0xc008a57900, 0xc002cb6270?, 0x0, 0xc00a23b808, 0x1?)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:437 +0xd85
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc007586738, 0x18}, 0x0, 0xc002cb6240)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:282 +0x79a
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc0078249c0, {0xc0111566d8, 0x16}, 0xc002cb6240, 0xc002cb6270, 0xc002cb62a0)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:334 +0x36d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc007667ec0, {0xc0111566d8, 0x16})
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x108cdca?, 0x0?, {0xc0111566d8?, 0xc00e756fd0?})
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:142 +0x11e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:129 +0x6ae

goroutine 818226 [sleep]:
time.Sleep(0x961dc414)
        runtime/time.go:194 +0x133
github.com/andres-erbsen/clock.(*clock).Sleep(0xc0b7580eb58d1d5c?, 0x61b64affad?)
        github.com/andres-erbsen/clock@v0.0.0-20160526145045-9e14626cd129/clock.go:40 +0x1c
go.uber.org/ratelimit.(*atomicLimiter).Take(0xc0001657a0)
        go.uber.org/ratelimit@v0.2.0/limiter_atomic.go:108 +0x1be
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc003c2e390, 0xb}, 0x0, 0xc00e6354d0)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:280 +0x6be
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc003c2b040, {0xc012a89800, 0x25}, 0xc00e6354d0, 0xc00e635500, 0xc00e635530)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:334 +0x36d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc00330e9e0, {0xc012a89800, 0x25})
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x108cdca?, 0x0?, {0xc012a89800?, 0xc00b2c5130?})
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:142 +0x11e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:129 +0x6ae

goroutine 816246 [runnable]:
internal/poll.runtime_pollWait(0x17ee653bde8, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00c387860?, 0xc00e6cc538?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc008038798, 0x2036478)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc008038780, {0xc00d0b352a, 0x1257, 0x1257})
        internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc008038780, {0xc00d0b352a?, 0x2030036?, 0xc00e6cc640?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc005a303a0, {0xc00d0b352a?, 0xc00dabedc0?, 0x0?})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc01264ef60, {0xc00d0b352a?, 0x0?, 0x17ee70c1cc8?})
        crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc009c7f3f8, {0x241e860, 0xc01264ef60})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc009c7f180, {0x2420ce0?, 0xc005a303a0}, 0xde4605?)
        crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc009c7f180, 0x0)
        crypto/tls/conn.go:659 +0xae5
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:582
crypto/tls.(*Conn).readHandshake(0xc009c7f180)
        crypto/tls/conn.go:1017 +0x6d
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc00e6cd140)
        crypto/tls/handshake_client.go:471 +0x45
crypto/tls.(*clientHandshakeState).handshake(0xc00e6cd140)
        crypto/tls/handshake_client.go:431 +0x3a5
crypto/tls.(*Conn).clientHandshake(0xc009c7f180, {0x2427980, 0xc0007e49c0})
        crypto/tls/handshake_client.go:230 +0x64a
crypto/tls.(*Conn).handshakeContext(0xc009c7f180, {0x24279f0, 0xc001bbcea0})
        crypto/tls/conn.go:1460 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
        crypto/tls/conn.go:1403
crypto/tls.dial({0x24279b8?, 0xc000036130?}, 0xc00008bb60, {0x1de62e0, 0x3}, {0xc00f494930, 0x12}, 0xc00b51e780)
        crypto/tls/tls.go:157 +0x3b1
crypto/tls.DialWithDialer(...)
        crypto/tls/tls.go:117
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).dial(0xc0002a6d80, {0x24279f0, 0xc002209260}, {0x1de62e0, 0x3}, {0xc00f494858?, 0x17ee59d56b0?}, 0x1, 0x0, 0xc00b51e480, ...)
        github.com/projectdiscovery/fastdialer@v0.0.16-0.20220609092737-7e3c7dcecf16/fastdialer/dialer.go:215 +0xc14
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).DialTLSWithConfig(...)
        github.com/projectdiscovery/fastdialer@v0.0.16-0.20220609092737-7e3c7dcecf16/fastdialer/dialer.go:121
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).DialTLS(0xc0002a6d80, {0x24279f0, 0xc002209260}, {0x1de62e0, 0x3}, {0xc00f494858, 0x15})
        github.com/projectdiscovery/fastdialer@v0.0.16-0.20220609092737-7e3c7dcecf16/fastdialer/dialer.go:110 +0x10a
net/http.(*Transport).customDialTLS(0xde7d75?, {0x24279f0?, 0xc002209260?}, {0x1de62e0?, 0xc00ac961a0?}, {0xc00f494858?, 0xc00eef3a20?})
        net/http/transport.go:1317 +0x50
net/http.(*Transport).dialConn(0xc0000a5040, {0x24279f0, 0xc002209260}, {{}, 0x0, {0xc00ae77710, 0x5}, {0xc00f494858, 0x15}, 0x0})
        net/http/transport.go:1583 +0x3ff
net/http.(*Transport).dialConnFor(0x2420f40?, 0xc008fa6d10)
        net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
        net/http/transport.go:1418 +0x3d2

goroutine 820900 [runnable]:
internal/poll.runtime_pollWait(0x17ee652a030, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x0?, 0x0?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc00647c518, 0x2036478)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc00647c500, {0xc00b30c000, 0x1429, 0x1429})
        internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc00647c500, {0xc00b30c000?, 0x3000b?, 0x400?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc001d7d2f0, {0xc00b30c000?, 0x400?, 0x400?})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc006e7bdd0, {0xc00b30c000?, 0x0?, 0x0?})
        crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc00ec93078, {0x241e860, 0xc006e7bdd0})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc00ec92e00, {0x2420ce0?, 0xc001d7d2f0}, 0xc0001016c0?)
        crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc00ec92e00, 0x0)
        crypto/tls/conn.go:614 +0x116
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc00ec92e00, {0xc0077e5000, 0x1000, 0x3d8?})
        crypto/tls/conn.go:1285 +0x16f
net/http.(*persistConn).Read(0xc0056ce480, {0xc0077e5000?, 0xd8591d?, 0x60?})
        net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc003f60de0)
        bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc003f60de0, 0x1)
        bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc0056ce480)
        net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
        net/http/transport.go:1750 +0x173e

goroutine 804762 [sleep]:
time.Sleep(0x91a7ad78)
        runtime/time.go:194 +0x133
github.com/andres-erbsen/clock.(*clock).Sleep(0xc0b7580ee1aed9c4?, 0x61de078615?)
        github.com/andres-erbsen/clock@v0.0.0-20160526145045-9e14626cd129/clock.go:40 +0x1c
go.uber.org/ratelimit.(*atomicLimiter).Take(0xc0001657a0)
        go.uber.org/ratelimit@v0.2.0/limiter_atomic.go:108 +0x1be
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc00204cc40, 0x1b}, 0x0, 0xc00aafecf0)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:280 +0x6be
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc00281a000, {0xc001f6d0a0, 0x1e}, 0xc00aafecf0, 0xc00aafed20, 0xc00aafed50)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:334 +0x36d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc0026db660, {0xc001f6d0a0, 0x1e})
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x108cdca?, 0x0?, {0xc001f6d0a0?, 0xc00b57da20?})
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:142 +0x11e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:129 +0x6ae

goroutine 816449 [select]:
net/http.(*Transport).getConn(0xc0000a5040, 0xc001bc2600, {{}, 0x0, {0xc004b70fc0, 0x5}, {0xc014d56330, 0x17}, 0x0})
        net/http/transport.go:1375 +0x5c6
net/http.(*Transport).roundTrip(0xc0000a5040, 0xc001ae9800)
        net/http/transport.go:581 +0x76f
net/http.(*Transport).RoundTrip(0xc001ae9800?, 0x2420da0?)
        net/http/roundtrip.go:17 +0x19
net/http.send(0xc00c765700, {0x2420da0, 0xc0000a5040}, {0x1da0f00?, 0xe54801?, 0x2dc55c0?})
        net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00091b3e0, 0xc00c765700, {0x50?, 0x2429908?, 0x2dc55c0?})
        net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00091b3e0, 0xc00c765700)
        net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        net/http/client.go:593
github.com/projectdiscovery/retryablehttp-go.(*Client).Do(0xc0002f43f0, 0xc002143170)
        github.com/projectdiscovery/retryablehttp-go@v1.0.3-0.20220506110515-811d938bd26d/do.go:64 +0x34b
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc000725380, {0xc00260ff40, 0x1f}, 0xc00fa10dc0, 0xc002142a20?, 0x1, 0xc00c667808, 0x1?)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:437 +0xd85
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc001e77e60, 0x5c}, 0x0, 0xc0021429f0)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:282 +0x79a
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc000725380, {0xc00260ff40, 0x1f}, 0xc0021429f0, 0xc002142a20, 0xc002142a80)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/request.go:334 +0x36d
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc003546040, {0xc00260ff40, 0x1f})
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:68 +0x1ae
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0xcdf1fd0?, 0xc0?, {0xc00260ff40?, 0xc00cc6c360?})
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:142 +0x11e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:129 +0x6ae

goroutine 816132 [runnable]:
internal/poll.runtime_pollWait(0x17ee5b62878, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x2431770?, 0x2431770?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc0036a2c98, 0x2036478)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc0036a2c80, {0xc00c7a54b6, 0x973, 0x973})
        internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc0036a2c80, {0xc00c7a54b6?, 0xc000180460?, 0xc006652640?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc00433a260, {0xc00c7a54b6?, 0xc006652620?, 0x17ee3a79908?})
        net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc0043b4db0, {0xc00c7a54b6?, 0x0?, 0x1825dff300000000?})
        crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc0095fb778, {0x241e860, 0xc0043b4db0})
        bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0095fb500, {0x2420ce0?, 0xc00433a260}, 0xde4605?)
        crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0095fb500, 0x0)
        crypto/tls/conn.go:659 +0xae5
crypto/tls.(*Conn).readRecord(...)
        crypto/tls/conn.go:582
crypto/tls.(*Conn).readHandshake(0xc0095fb500)
        crypto/tls/conn.go:1017 +0x6d
crypto/tls.(*clientHandshakeState).doFullHandshake(0xc00e447140)
        crypto/tls/handshake_client.go:471 +0x45
crypto/tls.(*clientHandshakeState).handshake(0xc00e447140)
        crypto/tls/handshake_client.go:431 +0x3a5
crypto/tls.(*Conn).clientHandshake(0xc0095fb500, {0x2427980, 0xc0019e5800})
        crypto/tls/handshake_client.go:230 +0x64a
crypto/tls.(*Conn).handshakeContext(0xc0095fb500, {0x24279f0, 0xc001ce90e0})
        crypto/tls/conn.go:1460 +0x32f
crypto/tls.(*Conn).HandshakeContext(...)
        crypto/tls/conn.go:1403
crypto/tls.dial({0x24279b8?, 0xc000036130?}, 0xc00008bb60, {0x1de62e0, 0x3}, {0xc014d57b60, 0x13}, 0xc00d5a4000)
        crypto/tls/tls.go:157 +0x3b1
crypto/tls.DialWithDialer(...)
        crypto/tls/tls.go:117
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).dial(0xc0002a6d80, {0x24279f0, 0xc003e37e00}, {0x1de62e0, 0x3}, {0xc00b17ab88?, 0x17ee5bc1480?}, 0x1, 0x0, 0xc005039b00, ...)
        github.com/projectdiscovery/fastdialer@v0.0.16-0.20220609092737-7e3c7dcecf16/fastdialer/dialer.go:215 +0xc14
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).DialTLSWithConfig(...)
        github.com/projectdiscovery/fastdialer@v0.0.16-0.20220609092737-7e3c7dcecf16/fastdialer/dialer.go:121
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).DialTLS(0xc0002a6d80, {0x24279f0, 0xc003e37e00}, {0x1de62e0, 0x3}, {0xc00b17ab88, 0x18})
        github.com/projectdiscovery/fastdialer@v0.0.16-0.20220609092737-7e3c7dcecf16/fastdialer/dialer.go:110 +0x10a
net/http.(*Transport).customDialTLS(0x0?, {0x24279f0?, 0xc003e37e00?}, {0x1de62e0?, 0x2426e90?}, {0xc00b17ab88?, 0xd902e8?})
        net/http/transport.go:1317 +0x50
net/http.(*Transport).dialConn(0xc0000a5040, {0x24279f0, 0xc003e37e00}, {{}, 0x0, {0xc0072f2d80, 0x5}, {0xc00b17ab88, 0x18}, 0x0})
        net/http/transport.go:1583 +0x3ff
net/http.(*Transport).dialConnFor(0x24213c0?, 0xc00c0ec160)
        net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
        net/http/transport.go:1418 +0x3d2

**Comment by ehsandeep** [comment]
@Ma1Dong Could you share additional/required information so we can start looking into this, what version of nuclei you were running and what' the input and command to replicate this?

**Comment by ehsandeep** [comment]
as of now moving this to discussion and will be moved to issue once confirmed.
