### ISSUE TITLE
Nuclei segmentation violation 

### ISSUE THREAD

**Issue by sullo** [projectdiscovery/nuclei#2817]
### Nuclei version:
[INF] Current Version: 2.7.8

### Current Behavior:
- When running against a particular group of hosts, nuclei crashes. 
- When run against each host individually, no crash happens.

### Expected Behavior:
Scan completes successfully.

### Steps To Reproduce:

- Command: `nuclei -l hosts.txt -t / -me nuclei-out/`
- hosts.txt has 24 entries in format `example.com`
- There happen to be 10 duplicates.
- I repeated the scan with the same results a second time.
- The target list contains `localhost` twice

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13faa21]

goroutine 40386 [running]:
github.com/openrdap/rdap/bootstrap.(*Client).Lookup(0xc00a3ac6f0, 0xc00a5368d0)
	/root/go/pkg/mod/github.com/openrdap/rdap@v0.9.1-0.20191017185644-af93e7ef17b7/bootstrap/client.go:340 +0x4e1
github.com/openrdap/rdap.(*Client).Do(0xc008c9ab70, 0xc011162fc0)
	/root/go/pkg/mod/github.com/openrdap/rdap@v0.9.1-0.20191017185644-af93e7ef17b7/client.go:150 +0x4fd
github.com/projectdiscovery/nuclei/v2/pkg/protocols/whois.(*Request).ExecuteWithResults(0xc006cf43c0, 0x203002?, 0x203002?, 0xc00a536600?, 0xc00a5366c0)
	/root/nuclei/v2/pkg/protocols/whois/whois.go:103 +0x208
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc0072b02c0, 0xc00a536600)
	/root/nuclei/v2/pkg/protocols/common/executer/executer.go:73 +0x1ea
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x2f267d0?, 0xc0?, {0xc015d167b0, 0x29})
	/root/nuclei/v2/pkg/core/execute.go:145 +0x176
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
	/root/nuclei/v2/pkg/core/execute.go:130 +0x6ae
```

**Comment by parrasajad** [comment]
seems related - #1816

**Comment by sullo** [comment]
> seems related - #1816

Definitely--didn't see that. I can reproduce it though.
