### ISSUE TITLE
Invalid URI in file causes segfault

### ISSUE THREAD

**Issue by MegaManSec** [projectdiscovery/nuclei#2996]
### Current Behavior:
using -l file.txt with a file containing: `https://~^(.*-pre)\.smth\.google\.com/` causes a segfault:
```
nuclei -t exposed-panels/grafana-detect.yaml -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0 SEC TEAM/JROGERS ON SLACK' -timeout 5  -l /tmp/test

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.1

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.1 (latest)
[INF] Using Nuclei Templates 9.3.1 (latest)
[INF] Templates added in last update: 2
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1b6c1d6]

goroutine 22 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/input.(*Helper).convertInputToType(0xc00000e0a8, {0xc005f56ae0, 0x26}, 0x4, {0x0, 0x0})
	github.com/projectdiscovery/nuclei/v2/pkg/input/input.go:72 +0x96
github.com/projectdiscovery/nuclei/v2/pkg/input.(*Helper).Transform(0x14?, {0xc005f56ae0?, 0x8?}, 0x0?)
	github.com/projectdiscovery/nuclei/v2/pkg/input/input.go:43 +0x7f
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc008a9ff00, 0xc0034a14c0)
	github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:75 +0x2c6
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x20649ca?, 0x0?, 0xc0034a1440)
	github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:146 +0x182
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
	github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:131 +0x745
```

### Expected Behavior:
safely fail

### Steps To Reproduce:
1. create file containing the string `https://~^(.*-pre)\.smth\.google\.com/`
2. run a template using that file.

**Comment by MegaManSec** [comment]
Happy to help. Not sure if it's relevant (I suppose not), but I'm on a Mac too, like that poster.
