### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by itsshoeb** [projectdiscovery/nuclei#3082]
### Nuclei version:
 Current Version: 2.8.3

### Current Behavior:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf637da]

goroutine 136 [running]:
net/url.(*URL).Hostname(...)
        /usr/lib/go-1.19/src/net/url/url.go:1144
github.com/projectdiscovery/nuclei/v2/pkg/input.(*Helper).convertInputToType(0xc000510fa0, {0xc008972060, 0x2c}, 0x1, {0x0, 0x0})
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.3/pkg/input/input.go:97 +0x21a
github.com/projectdiscovery/nuclei/v2/pkg/input.(*Helper).Transform(0x0?, {0xc008972060?, 0x0?}, 0x0?)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.3/pkg/input/input.go:39 +0xca
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc0031efc60, 0xc0088ddba0)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.3/pkg/protocols/common/executer/executer.go:75 +0x2c6
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x0?, 0x0?, 0xc0088ddb00)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.3/pkg/core/execute.go:146 +0x182
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.3/pkg/core/execute.go:131 +0x745
```

### Expected Behavior:
 Nuclei should show the findings

**Comment by ehsandeep** [comment]
@itsshoeb can you also share nuclei cmd you used or we can use to reproduce this?

**Comment by tarunKoyalwar** [comment]
seems like another case where `url.Parse` fails to parse URL  https://github.com/projectdiscovery/nuclei/issues/2979 https://github.com/projectdiscovery/nuclei/pull/3004 Extra error handling should solve this

**Comment by tarunKoyalwar** [comment]
@itsshoeb , fix is available on branch `issue-3082-url-panic` can you verify it after installing dev version using

```sh
 go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@5461c29    
```

This should solve it . can you confirm it and pls share if you still facing problems this panic is related to `url` so if you share your input url or a specific url that fails it will be easy to fix
