### ISSUE TITLE
crash of nuclei

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/nuclei#3179]
### Nuclei version:
[INF] Using Nuclei Engine 2.8.6 (latest)
[INF] Using Nuclei Templates 9.3.4 (latest)

### Current Behavior:

I am running nuclei and encountering this error `nuclei -ss host-spray -etags dos -concurrency 150 -bulk-size 10 -o output`

```
panic: sync: WaitGroup is reused before previous Wait has returned

github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1.1(0x0?)
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:70 +0x7c
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:68 +0x1e5
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 564 [running]:
sync.(*WaitGroup).Wait(0x13fc4d6?)
        /usr/local/go/src/sync/waitgroup.go:141 +0x85
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Wait(...)
        /home/op/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:83
github.com/projectdiscovery/nuclei/v2/pkg/core.(*WorkPool).Wait(0xc001250ed0)
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/workpool.go:46 +0x2b
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateSpray(0xc00051ad00, {0xc007eca000, 0x236, 0x0?}, {0x28845f0?, 0xc005c2a558})
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:53 +0x277
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1.1(0xc001985000?)
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:70 +0x7c
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:68 +0x1e5
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 563 [running]:
sync.(*WaitGroup).Wait(0x13fc4d6?)
        /usr/local/go/src/sync/waitgroup.go:141 +0x85
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Wait(...)
        /home/op/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:83
github.com/projectdiscovery/nuclei/v2/pkg/core.(*WorkPool).Wait(0xc001f6dd70)
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/workpool.go:46 +0x2b
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateSpray(0xc00085ad00, {0xc0072fd900, 0x236, 0xc0070f6b30?}, {0x28845f0?, 0xc0088b85b8})
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:53 +0x277
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1.1(0x206f6d5?)
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:70 +0x7c
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:68 +0x1e5

panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 565 [running]:
sync.(*WaitGroup).Wait(0x13fc4d6?)
        /usr/local/go/src/sync/waitgroup.go:141 +0x85
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Wait(...)
        /home/op/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:83
github.com/projectdiscovery/nuclei/v2/pkg/core.(*WorkPool).Wait(0xc0011263c0)
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/workpool.go:46 +0x2b
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateSpray(0xc0008f89c0, {0xc007793300, 0x236, 0x0?}, {0x28845f0?, 0xc00216ea20})
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:53 +0x277
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1.1(0x0?)
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:70 +0x7c
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeHostSpray.func1
        /home/op/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.6/pkg/core/execute.go:68 +0x1e5
```

### Expected Behavior:
 not to crash

### Steps To Reproduce:

Not sure how to detail the steps to reproduce. It isn't happening all the time and in all of my vps.

**Comment by marcelo321** [comment]
Closing because I think it was my issue.

**Comment by ehsandeep** [comment]
Related issue - https://github.com/projectdiscovery/nuclei/issues/3140
