### ISSUE TITLE
Exception when passing invalid config

### ISSUE THREAD

**Issue by yaabdala** [projectdiscovery/nuclei#3224]
### Nuclei version:
2.8.7

### Current Behavior:
When running nuclei using a config file that specifies a target file like
```
# path to file containing a list of target urls/hosts to scan (one per line)
list: ./nuclei-targets.txt
```
Nuclei with throw an exception instead of gracefully handling the error

```
(oath_tools) (base) ➜  nuclei git:(dev) ✗ ~/go/bin/nuclei -config config.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.7

		projectdiscovery.io

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x100788c1a]

goroutine 1 [running]:
github.com/projectdiscovery/nuclei/v2/internal/runner/nucleicloud.(*Client).ExistsDataSourceItem(0x0, {{0x101c94c42?, 0x1024be260?}, {0xc00004c468?, 0xc0005b5ad0?}})
	/Users/aabdala/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.7/internal/runner/nucleicloud/cloud.go:263 +0x13a
github.com/projectdiscovery/nuclei/v2/internal/runner.New.func2({0xc00004c468, 0x14})
	/Users/aabdala/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.7/internal/runner/runner.go:193 +0x70
github.com/projectdiscovery/nuclei/v2/pkg/core/inputs/hybrid.(*Input).initializeInputSources(0x0?, 0xc0005b5dc0)
	/Users/aabdala/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.7/pkg/core/inputs/hybrid/hmap.go:129 +0x16a
github.com/projectdiscovery/nuclei/v2/pkg/core/inputs/hybrid.New(0xc0005b5dc0)
	/Users/aabdala/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.7/pkg/core/inputs/hybrid/hmap.go:86 +0x26f
github.com/projectdiscovery/nuclei/v2/internal/runner.New(0x10343a960)
	/Users/aabdala/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.7/internal/runner/runner.go:188 +0x745
main.main()
	/Users/aabdala/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.8.7/cmd/nuclei/main.go:75 +0x389
```

### Expected Behavior:
Nuclei should parse the config file and validate that the file exists. If it doesn't exist, it should print a helpful error

### Steps To Reproduce:

1. create a config file from the template in `./.config/nuclei/config.yaml`
2. Uncomment `list:` and give a file name that doesn't exist
3. run nuclei with the `-config ./config.yaml` flag

**Comment by jimen0** [comment]
This is the same as #3194 and was fixed by https://github.com/projectdiscovery/nuclei/commit/7200e83d47aa113bf98b49ab883e70130ae2ab69.

cc @Ice3man543
