### ISSUE TITLE
invalid memory address or nil pointer dereference (CI Test)

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#3423]
### Nuclei version:
dev

### Current Behavior:
CI test getting failed on windows env

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x101ee55]

goroutine 1 [running]:
main.executeNucleiAsCode({0x1437fee, 0xe}, {0xc0004fc000, 0x16})
	C:/a/nuclei/nuclei/v2/cmd/integration-test/code.go:73 +0xf5
main.(*goIntegrationTest).Execute(0xc0011c9c78?, {0x1437fee, 0xe})
	C:/a/nuclei/nuclei/v2/cmd/integration-test/code.go:59 +0xd0
main.execute({0x19050a0?, 0x2342e90?}, {0x1437fee, 0xe})
	C:/a/nuclei/nuclei/v2/cmd/integration-test/integration-test.go:111 +0x55
main.runTests(0xc0011c9eb0)
	C:/a/nuclei/nuclei/v2/cmd/integration-test/integration-test.go:100 +0x2b1
main.main()
	C:/a/nuclei/nuclei/v2/cmd/integration-test/integration-test.go:[65](https://github.com/projectdiscovery/nuclei/actions/runs/4415887657/jobs/7739438592#step:7:69) +0x27f
```

### Expected Behavior:

Tests are passing. 

### Steps To Reproduce:
https://github.com/projectdiscovery/nuclei/actions/runs/4415887657/jobs/7739438592

**Comment by tarunKoyalwar** [comment]
@ehsandeep  this should be fixed with https://github.com/projectdiscovery/nuclei/pull/3421
