### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by realalexandergeorgiev** [projectdiscovery/nuclei#3476]
### Nuclei version:
`[INF] Current Version: 2.9.0`

### Current Behavior:
crashing while scanning a large list

### Expected Behavior:
at least try catch around expression

### Steps To Reproduce:
`nuclei -stats -rl 50 -retries 30 -mhe 10 -report-db db -markdown-export nuclei-md-out/ -l nuclei-quick.ip -o nuclei-scan -ni`

### Anything else:
fails somewhere parsing client certificate
```
[ssl-dns-names] [ssl] [info] 10.10.10.10:443 [XXXXXX]
[ssl-issuer] [ssl] [info] 10.10.10.10:443 [XXXXX]
[untrusted-root-certificate] [ssl] [low] 10.10.10.10:443

panic: runtime error: slice bounds out of range [:-1]

goroutine 151770 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.FormatToSerialNumber(0xc00704470a?)
	/build/nuclei-zCBxlp/nuclei-2.9.0/vendor/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/clients/utils.go:103 +0x1ac
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.Convertx509toResponse(0xc010ac4948?, {0xc00d5e0a98, 0xe}, 0xc00960e680, 0x0)
	/build/nuclei-zCBxlp/nuclei-2.9.0/vendor/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/clients/utils.go:35 +0x33a
github.com/projectdiscovery/tlsx/pkg/tlsx/tls.(*Client).ConnectWithOptions(0xc00a11dd70, {0xc00d5e0a98, 0xe}, {0xc00d5e0a98, 0xe}, {0xc00d5e0aa7, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/build/nuclei-zCBxlp/nuclei-2.9.0/vendor/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tls/tls.go:153 +0x7ff
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc00a11dda0, {0xc00d5e0a98, 0xe}, {0xc00d5e0a98, 0xe}, {0xc00d5e0aa7, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/build/nuclei-zCBxlp/nuclei-2.9.0/vendor/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/auto/auto.go:42 +0xb8
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc00a11dd58, {0xc00d5e0a98, 0xe}, {0xc00d5e0a98, 0xe}, {0xc00d5e0aa7, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
	/build/nuclei-zCBxlp/nuclei-2.9.0/vendor/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
	/build/nuclei-zCBxlp/nuclei-2.9.0/vendor/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc009b86380, 0xc00ae91be0, 0x7f883e79c108?, 0x20?, 0xc005868e70)
	/build/nuclei-zCBxlp/nuclei-2.9.0/v2/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/templates.(*ClusterExecuter).Execute(0xc005cb49c0, 0xc00ae91b80)
	/build/nuclei-zCBxlp/nuclei-2.9.0/v2/pkg/templates/cluster.go:245 +0x22d
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0xffffffff?, 0xff?, 0xc008ffc160)
	/build/nuclei-zCBxlp/nuclei-2.9.0/v2/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
	/build/nuclei-zCBxlp/nuclei-2.9.0/v2/pkg/core/executors.go:105 +0x4f8
```

**Comment by Mzack9999** [comment]
This will be indirectly fixed with new tlsx release tag

**Comment by realalexandergeorgiev** [comment]
how can i test this? the tlsx patch?

**Comment by realalexandergeorgiev** [comment]
as described tlsx patch fixed the issue
