### ISSUE TITLE
Error during scanning

### ISSUE THREAD

**Issue by test502git** [projectdiscovery/nuclei#3481]
Error during scanning
nuclei -l urls.txt  -stats 
scaning 
 ....
```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf67c1a]

goroutine 464001 [running]:
net/url.(*URL).Hostname(...)
        net/url/url.go:1133
github.com/projectdiscovery/nuclei/v2/pkg/input.(*Helper).convertInputToType(0xc000240098, {0xc0059e78f0, 0x21}, 0x1, {0x0, 0x0})
        github.com/projectdiscovery/nuclei/v2/pkg/input/input.go:97 +0x21a
github.com/projectdiscovery/nuclei/v2/pkg/input.(*Helper).Transform(0x447bf3?, {0xc0059e78f0?, 0x8?}, 0x705e3d?)
        github.com/projectdiscovery/nuclei/v2/pkg/input/input.go:39 +0xc5
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc0052af240, 0xc0055e9900)
        github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer/executer.go:75 +0x2c6
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2.1(0x72b166?, 0x0?, 0xc00928dce0)
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:146 +0x182
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeModelWithInput.func2
        github.com/projectdiscovery/nuclei/v2/pkg/core/execute.go:131 +0x745
```

**Comment by ehsandeep** [comment]
@test502git what version of nuclei you running?

**Comment by ducducuc111** [comment]
- I get the same issue when using flag **_-stats_**. The process run as usual, but it stoped when almost finish.
- I'm using **_Nuclei v 2.9 (lastest)_**
- Here the command I use: `nuclei -l test.txt -t ~/nuclei-templates/ -s critical -stats` (**medium**, **high** will get same issue).


![Error](https://user-images.githubusercontent.com/52061565/228880112-36762ed0-271e-4059-84d3-54611764685e.jpg)

**Comment by ehsandeep** [comment]
@test502git, you are running an outdated version of nuclei, it was fixed in https://github.com/projectdiscovery/nuclei/issues/3082, make sure to update to latest version.
