### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei#3487]
### Current Behavior:
crashing while scanning a large list

### Expected Behavior:
Maybe is good periodically to save resume file so if crashes like in this case we can resume from last saved point

### Steps To Reproduce:
`cat ips.txt | nuclei -t cves -t exposures -t default-logins -t vulnerabilities -t exposed-panels -t file -stats -rl 4000 -o ips.nuclei
`
### Anything else:
fails somewhere parsing client certificate

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 344683378 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.FormatToSerialNumber(0x4004a5b8cb?)
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/clients/utils.go:103 +0x188
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.Convertx509toResponse(0x402ece5cc8?, {0x4043f45ee0, 0x8}, 0x4020bca100, 0x0)
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/clients/utils.go:35 +0x2a8
github.com/projectdiscovery/tlsx/pkg/tlsx/tls.(*Client).ConnectWithOptions(0x400379bcf8, {0x4043f45ee0, 0x8}, {0x4043f45ee0, 0x8}, {0x4043f45ee9, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tls/tls.go:153 +0x620
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0x400379bd58, {0x4043f45ee0, 0x8}, {0x4043f45ee0, 0x8}, {0x4043f45ee9, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/auto/auto.go:42 +0x90
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0x400379bce0, {0x4043f45ee0, 0x8}, {0x4043f45ee0, 0x8}, {0x4043f45ee9, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tlsx.go:74 +0x1c4
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0x400018ca80, 0x400737a600, 0xffff6171fec0?, 0xffff89410108?, 0x401ed71020)
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.0/pkg/protocols/ssl/ssl.go:218 +0x4c8
github.com/projectdiscovery/nuclei/v2/pkg/templates.(*ClusterExecuter).Execute(0x4001cfc400, 0x400737a5a0)
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.0/pkg/templates/cluster.go:245 +0x244
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x21f16480?, 0x40?, 0x4005a1bc20)
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.0/pkg/core/executors.go:128 +0x23c
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /home/ubuntu/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.0/pkg/core/executors.go:105 +0x430
```

**Comment by ehsandeep** [comment]
@mastercho this is fixed in the latest release.

**Comment by mastercho** [comment]
> @mastercho this is fixed in the latest release.

happen again on dev branch latest commit [bca0c53a41e2d8cd58779369eb948dacfec360d7](https://github.com/projectdiscovery/nuclei/commit/bca0c53a41e2d8cd58779369eb948dacfec360d7)

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 12645357 [running]:
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.FormatToSerialNumber(0xc00c4db00a?)
        /root/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/clients/utils.go:103 +0x189
github.com/projectdiscovery/tlsx/pkg/tlsx/clients.Convertx509toResponse(0xc04ab7e1b0?, {0xc00677d710, 0xd}, 0xc02a3cab00, 0x0)
        /root/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/clients/utils.go:35 +0x37a
github.com/projectdiscovery/tlsx/pkg/tlsx/tls.(*Client).ConnectWithOptions(0xc0027a9320, {0xc00677d710, 0xd}, {0xc00677d710, 0xd}, {0xc00677d71e, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
        /root/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tls/tls.go:153 +0x7ff
github.com/projectdiscovery/tlsx/pkg/tlsx/auto.(*Client).ConnectWithOptions(0xc0027a94d0, {0xc00677d710, 0xd}, {0xc00677d710, 0xd}, {0xc00677d71e, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
        /root/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/auto/auto.go:42 +0xb8
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).ConnectWithOptions(0xc0027a9218, {0xc00677d710, 0xd}, {0xc00677d710, 0xd}, {0xc00677d71e, 0x3}, {{0x0, 0x0}, {0x0, ...}, ...})
        /root/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tlsx.go:74 +0x243
github.com/projectdiscovery/tlsx/pkg/tlsx.(*Service).Connect(...)
        /root/go/pkg/mod/github.com/projectdiscovery/tlsx@v1.0.6/pkg/tlsx/tlsx.go:60
github.com/projectdiscovery/nuclei/v2/pkg/protocols/ssl.(*Request).ExecuteWithResults(0xc0003149a0, 0xc02f9194e0, 0x7fdcca7316a0?, 0x7fdcf3b6f108?, 0xc02f9092a8)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230413124104-bca0c53a41e2/pkg/protocols/ssl/ssl.go:218 +0x62d
github.com/projectdiscovery/nuclei/v2/pkg/templates.(*ClusterExecuter).Execute(0xc0078f1840, 0xc02f919480)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230413124104-bca0c53a41e2/pkg/templates/cluster.go:245 +0x22d
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x7566a6?, 0x0?, 0xc02cd18c00)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230413124104-bca0c53a41e2/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.1-0.20230413124104-bca0c53a41e2/pkg/core/executors.go:105 +0x4f8
```
