### ISSUE TITLE
nuclei projectdiscovery/retryablehttp-go transport goroutine leak

### ISSUE THREAD

**Issue by samy1937** [projectdiscovery/nuclei#3535]
goroutine 17039631 [semacquire]:
sync.runtime_SemacquireMutex(0xc046e8c180?, 0x1e?, 0xc002f34000?)
        D:/go/go1.18/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00032a3f0)
        D:/go/go1.18/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
        D:/go/go1.18/src/sync/mutex.go:81
net/http.(*Transport).setReqCanceler(0xc00032a3c0, {0xc009abaa80?}, 0x0)
        D:/go/go1.18/src/net/http/transport.go:1134 +0x5e
net/http.(*Transport).roundTrip(0xc00032a3c0, 0xc0288d0800)
        D:/go/go1.18/src/net/http/transport.go:583 +0x9a6
net/http.(*Transport).RoundTrip(0xc0288d0800?, 0x33d0e80?)
        D:/go/go1.18/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc028780600, {0x33d0e80, 0xc00032a3c0}, {0x248dee0?, 0xb31901?, 0x3f305c0?})
        D:/go/go1.18/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00047fdd0, 0xc028780600, {0x50?, 0x2278e00?, 0x3f305c0?})
        D:/go/go1.18/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00047fdd0, 0xc028780600)
        D:/go/go1.18/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        D:/go/go1.18/src/net/http/client.go:593
github.com/projectdiscovery/retryablehttp-go.(*Client).Do(0xc001464120, 0xc0194885d0)
        D:/go/src/github.com/xxxx/xxx/vendor/github.com/projectdiscovery/retryablehttp-go/do.go:52 +0x239

**Comment by olearycrew** [comment]
@samy1937 can you add some details around what you were doing to get this error and how to reproduce it?

A good guide for the information we need to help would include the items in this issue template: https://github.com/projectdiscovery/nuclei/blob/main/.github/ISSUE_TEMPLATE/issue-report.md

Thanks!
