### ISSUE TITLE
[ERR] Detected hanging goroutine

### ISSUE THREAD

**Issue by praetorian-thendrickson** [projectdiscovery/nuclei#3758]
### Nuclei version:

v2.9.5 (`projectdiscovery/nuclei:latest` docker image)

### Current Behavior:
I've been using nuclei in a few scripts, and have been observing repeated crashing / deadlocking behavior. Running nuclei on my scan input (often a few hundred different input urls) results in roughly 20% of the nuclei scans failing with the following behavior:
```
[ERR] Detected hanging goroutine (count=27/27) = nuclei-stacktrace-chr0roqa9nls76o7e1i0.dump
```
Originally, I noticed the scans were getting stuck indefinitely, then I ran with the `-hang-monitor` option to output the trace. I've been reproducing it reliably locally.

### Expected Behavior:
Nuclei not to deadlock and crash.

### Steps To Reproduce:
1. `docker run -m 256m --cpus "0.25" --rm -it --entrypoint /bin/sh -v $(pwd):/config projectdiscovery/nuclei:latest` -- start docker container with the newest nuclei image. The memory/cpu constraints allow more reliable reproduction of the crash behavior
2. `echo "https://tesla.com" | nuclei -jsonl -include-rr -rl 1000 -c 1 -hang-monitor` -- start the nuclei scan
3. Wait, and observe the crash expecting:
```
[ERR] Detected hanging goroutine (count=27/27) = nuclei-stacktrace-chr0roqa9nls76o7e1i0.dump
```
and a stack trace that looks like:
```golang
goroutine 41 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/utils/monitor.glob..func1(0x0?)
	/app/v2/pkg/utils/monitor/monitor.go:93 +0x50
github.com/projectdiscovery/nuclei/v2/pkg/utils/monitor.(*Agent).monitorWorker(0xc000550ab0)
	/app/v2/pkg/utils/monitor/monitor.go:71 +0xc2
github.com/projectdiscovery/nuclei/v2/pkg/utils/monitor.NewStackMonitor.func1()
	/app/v2/pkg/utils/monitor/monitor.go:43 +0x98
created by github.com/projectdiscovery/nuclei/v2/pkg/utils/monitor.NewStackMonitor
	/app/v2/pkg/utils/monitor/monitor.go:37 +0xf8

goroutine 1 [select]:
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).AddWithContext(0xc00657b860, {0x28a8c90, 0xc00012e000})
	/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:63 +0x78
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Add(...)
	/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:51
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateSpray(0xc00080a380, {0xc00521a000, 0x100f, 0xc00a63e9c8?}, {0x28a6c10?, 0xc000306500})
	/app/v2/pkg/core/execute_options.go:96 +0x16a
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).ExecuteScanWithOpts(0xc00080a380, {0xc00539e000, 0x137a, 0x1746}, {0x28a6c10, 0xc000306500}, 0x1)
	/app/v2/pkg/core/execute_options.go:67 +0x5ae
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).executeTemplatesInput(0xc000317080, 0xc000178750, 0xc00080a380)
	/app/v2/internal/runner/runner.go:687 +0x42c
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).runStandardEnumeration(_, {{0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {{0x0, 0x0}}, {{0x0, ...}}, ...}, ...}, ...)
	/app/v2/internal/runner/enumerate.go:34 +0x6d
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration(0xc000317080)
	/app/v2/internal/runner/runner.go:573 +0x1694
main.main()
	/app/v2/cmd/nuclei/main.go:102 +0x539

goroutine 36 [select]:
github.com/projectdiscovery/ratelimit.(*Limiter).run(0xc000a99ac0, {0x28a8c58, 0xc000a92050})
	/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.6/ratelimit.go:27 +0x16e
created by github.com/projectdiscovery/ratelimit.New
	/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.6/ratelimit.go:93 +0x185

goroutine 7 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000a301c0)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c

goroutine 8 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000531380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x137
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea

goroutine 9 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000531380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a

goroutine 10 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000531380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x6b7
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x59b

goroutine 11 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000531380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d8

goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc000a30380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c

goroutine 37 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000531d40)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x137
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea

goroutine 38 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc000531d40)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a

goroutine 39 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc000531d40)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x6b7
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x59b

goroutine 40 [select, 6 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc000531d40)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d8

goroutine 27 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc00002a000)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xc7
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x18c

goroutine 28 [select, 5 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc0003a1380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x137
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x4ea

goroutine 29 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc0003a1380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0xa8
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x52a

goroutine 30 [select, 5 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc0003a1380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x6b7
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x59b

goroutine 31 [select, 5 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc0003a1380)
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0x113
created by github.com/syndtr/goleveldb/leveldb.openDB
	/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x5d8

goroutine 82 [select]:
github.com/projectdiscovery/ratelimit.(*Limiter).run(0xc000306640, {0x28a8c58, 0xc000096eb0})
	/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.6/ratelimit.go:27 +0x16e
created by github.com/projectdiscovery/ratelimit.New
	/go/pkg/mod/github.com/projectdiscovery/ratelimit@v0.0.6/ratelimit.go:93 +0x185

goroutine 98 [syscall, 5 minutes]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x2a

goroutine 99 [chan receive, 5 minutes]:
main.main.func2()
	/app/v2/cmd/nuclei/main.go:88 +0x6b
created by main.main
	/app/v2/cmd/nuclei/main.go:87 +0x52c

goroutine 2231 [select]:
github.com/projectdiscovery/interactsh/pkg/client.(*Client).StartPolling.func1()
	/go/pkg/mod/github.com/projectdiscovery/interactsh@v1.1.4/pkg/client/client.go:356 +0x111
created by github.com/projectdiscovery/interactsh/pkg/client.(*Client).StartPolling
	/go/pkg/mod/github.com/projectdiscovery/interactsh@v1.1.4/pkg/client/client.go:350 +0x1b1

goroutine 2230 [select]:
github.com/projectdiscovery/interactsh/pkg/client.New.func1()
	/go/pkg/mod/github.com/projectdiscovery/interactsh@v1.1.4/pkg/client/client.go:185 +0x133
created by github.com/projectdiscovery/interactsh/pkg/client.New
	/go/pkg/mod/github.com/projectdiscovery/interactsh@v1.1.4/pkg/client/client.go:179 +0x5fb

goroutine 3198 [IO wait]:
internal/poll.runtime_pollWait(0x7f7f411f5aa8, 0x77)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc00737f780?, 0x0?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitWrite(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:93
internal/poll.(*FD).WaitWrite(...)
	/usr/local/go/src/internal/poll/fd_unix.go:741
net.(*netFD).connect(0xc00737f780, {0x28a8cc8?, 0xc00a0b0b70}, {0x7f7f411f5aa8?, 0xc001df2590?}, {0x2898900?, 0xc00a9851e0?})
	/usr/local/go/src/net/fd_unix.go:141 +0x799
net.(*netFD).dial(0xc00737f780, {0x28a8cc8, 0xc00a0b0b70}, {0x28ad068?, 0x0?}, {0x28ad068?, 0xc00a0b0bd0}, 0xc008d3a9a0?)
	/usr/local/go/src/net/sock_posix.go:151 +0x3c5
net.socket({0x28a8cc8, 0xc00a0b0b70}, {0x1fd14fa, 0x3}, 0x2, 0x1, 0x417b10?, 0xab?, {0x28ad068, 0x0}, ...)
	/usr/local/go/src/net/sock_posix.go:70 +0x2d2
net.internetSocket({0x28a8cc8, 0xc00a0b0b70}, {0x1fd14fa, 0x3}, {0x28ad068, 0x0}, {0x28ad068, 0xc00a0b0bd0}, 0xc00c5ad820?, 0x0, ...)
	/usr/local/go/src/net/ipsock_posix.go:142 +0xf8
net.(*sysDialer).doDialTCP(0xc0070e63f0, {0x28a8cc8, 0xc00a0b0b70}, 0x0, 0x0?)
	/usr/local/go/src/net/tcpsock_posix.go:74 +0xef
net.(*sysDialer).dialTCP(0xc001df2868?, {0x28a8cc8?, 0xc00a0b0b70?}, 0x524786?, 0xaa?)
	/usr/local/go/src/net/tcpsock_posix.go:64 +0x69
net.(*sysDialer).dialSingle(0xc0070e63f0, {0x28a8cc8, 0xc00a0b0b70}, {0x28a3f70?, 0xc00a0b0bd0})
	/usr/local/go/src/net/dial.go:580 +0x1f2
net.(*sysDialer).dialSerial(0xc0070e63f0, {0x28a8cc8, 0xc00a0b0b70}, {0xc00abb1920?, 0x1, 0x417b10?})
	/usr/local/go/src/net/dial.go:548 +0x245
net.(*sysDialer).dialParallel(0xc00abb1910?, {0x28a8cc8?, 0xc00a0b0b70?}, {0xc00abb1920?, 0xc00a0b0b70?, 0x1fd451c?}, {0x0?, 0x1fd14fa?, 0x10?})
	/usr/local/go/src/net/dial.go:449 +0x413
net.(*Dialer).DialContext(0xc000968070, {0x28a8c90, 0xc00012e000}, {0x1fd14fa, 0x3}, {0xc00c5ad800, 0x10})
	/usr/local/go/src/net/dial.go:440 +0x70c
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).dial(0xc00056e800, {0x28a8c90, 0xc00012e000}, {0x1fd14fa, 0x3}, {0xc009f295a0, 0xe}, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.0.26/fastdialer/dialer.go:266 +0xd91
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).Dial(...)
	/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.0.26/fastdialer/dialer.go:112
github.com/projectdiscovery/nuclei/v2/pkg/protocols/network.(*Request).executeRequestWithPayloads(0xc00329ba00, 0xc001df3800, {0xc009f295a0, 0xe}, {0xc009f28d10, 0xd}, {0xc009f28d10, 0xd}, 0x0, 0xc00b362900, ...)
	/app/v2/pkg/protocols/network/request.go:118 +0x153
github.com/projectdiscovery/nuclei/v2/pkg/protocols/network.(*Request).executeAddress(0xc00329ba00, 0xc001df3c10, {0xc009f295a0, 0xe}, {0xc009f28d10, 0xd}, {0xc009f28d10, 0xd}, 0x10?, 0xc00a3cbb90, ...)
	/app/v2/pkg/protocols/network/request.go:97 +0x666
github.com/projectdiscovery/nuclei/v2/pkg/protocols/network.(*Request).ExecuteWithResults(0xc00329ba00, 0xc00c0c76e0, 0xc0071845f8?, 0x44b4d3?, 0x43bb36?)
	/app/v2/pkg/protocols/network/request.go:62 +0x3b6
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc001aaed40, 0xc00c0c7680)
	/app/v2/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x16164ea?, 0x0?, 0xc00c0c7600)
	/app/v2/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
	/app/v2/pkg/core/executors.go:105 +0x4f8

goroutine 3429 [select]:
net.(*netFD).connect.func2()
	/usr/local/go/src/net/fd_unix.go:118 +0x86
created by net.(*netFD).connect
	/usr/local/go/src/net/fd_unix.go:117 +0x3bd

goroutine 3197 [semacquire]:
sync.runtime_Semacquire(0x48?)
	/usr/local/go/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc000306500?)
	/usr/local/go/src/sync/waitgroup.go:116 +0x4b
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Wait(...)
	/go/pkg/mod/github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:83
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets(0xc00080a380, 0xc003c4dd40, {0x28a6c10, 0xc000306500}, 0xc0073b65b0)
	/app/v2/pkg/core/executors.go:139 +0x491
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateSpray.func1(0xc009c9b680?)
	/app/v2/pkg/core/execute_options.go:102 +0x6e
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateSpray
	/app/v2/pkg/core/execute_options.go:97 +0x67
```
4. If it doesn't error, just restart the scan (it errors locally for me most (80%) of the time).

### Anything else:
This looks similar to the other issue: https://github.com/projectdiscovery/nuclei/issues/3524. I also attempted to modify the `-c` option in case that was related, but it still crashes with various values (1, 10, 25).

**Comment by tarunKoyalwar** [comment]
@praetorian-thendrickson , thanks for providing issue with great detail but changing concurrency to `-1` is not recommended in any situations.

### What is hang-monitor ??
simply put it is used to detect block/ hanged goroutines.  when we run nuclei scan on a target it sends a request to server for every (target * template) combination . and all this happens async (concurrent) . if scan gets stuck and is not moving to next target+template combination then that is problem and this can be detected by hang monitor

the hang situation happens due to multiple reasons and and is prone to false positives. some of those situations are
- timeout related (current case)
- deadlock or some kind of blocking (very rare)

### How does it work ?
it checks if data (stack) of a [xyz] goroutine is same for at least 10 sec . if so it is considered as hang

### False Positives
as i was mentioning there are many false positives cases for hang-monitor. 
ex: server responds very slowly ~30 sec , connection is not closed properly (waiting for timeout), etc.

>Note: changing concurrency to `1` or using race detectors `-race` only increase changes of false positives. hence those are discouraged

### Is this False Positive ??
At first it felt false positive since hang monitor time == 10 sec and default timeout == 10 sec . after multiple tries found issue for that . it is being tracked at #3762
