### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by TheTechromancer** [projectdiscovery/nuclei#3797]
Command: `nuclei -s high,critical -etags intrusive -l urls.txt -stats -o nuclei0.txt -rl 500`
Nuclei version: `v2.9.6`
Installation method: `go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest`
Golang version: `go1.20.4`
Platform: `linux/amd64`

```
[3:15:35] | Templates: 1900 | Hosts: 12315 | RPS: 487 | Matched: 24 | Errors: 227005 | Requests: 5718414/40553295 (14%)
[3:15:40] | Templates: 1900 | Hosts: 12315 | RPS: 487 | Matched: 24 | Errors: 227057 | Requests: 5720874/40553295 (14%)
[3:15:45] | Templates: 1900 | Hosts: 12315 | RPS: 487 | Matched: 24 | Errors: 227111 | Requests: 5723292/40553295 (14%)
[3:15:50] | Templates: 1900 | Hosts: 12315 | RPS: 487 | Matched: 24 | Errors: 227155 | Requests: 5725751/40553295 (14%)
panic: runtime error: slice bounds out of range [154612:0]

goroutine 75796463 [running]:
bytes.(*Buffer).grow(0xc00d700840, 0x25bf4)
        /usr/lib/go/src/bytes/buffer.go:137 +0x21c
bytes.(*Buffer).Write(0xc00d700840, {0xc01bdca000, 0x25bf4, 0x418901?})
        /usr/lib/go/src/bytes/buffer.go:170 +0x66
bytes.(*Buffer).WriteTo(0xc00d700870, {0x2896f40?, 0xc00d700840?})
        /usr/lib/go/src/bytes/buffer.go:252 +0x83
io.copyBuffer({0x2896f40, 0xc00d700840}, {0x2896f20, 0xc00d700870}, {0x0, 0x0, 0x0})
        /usr/lib/go/src/io/io.go:409 +0x16e
io.Copy(...)
        /usr/lib/go/src/io/io.go:386
github.com/projectdiscovery/utils/reader.ReusableReadCloser.reset({0xc00b9e6300, {0x289b980, 0xc0133e0c60}, 0xc00d700840, 0xc00d700870})
        /root/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.34/reader/reusable_read_closer.go:95 +0xa8
github.com/projectdiscovery/utils/reader.ReusableReadCloser.Read({0xc00b9e6300, {0x289b980, 0xc0133e0c60}, 0xc00d700840, 0xc00d700870}, {0xc01e3c4dfa?, 0xc007506cd8?, 0x48450f?})
        /root/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.34/reader/reusable_read_closer.go:86 +0xb3
bytes.(*Buffer).ReadFrom(0xc007506d60, {0x289aae0, 0xc00d7008a0})
        /usr/lib/go/src/bytes/buffer.go:202 +0x98
github.com/projectdiscovery/retryablehttp-go.(*Request).BodyBytes(0xc00fbaff20?)
        /root/go/pkg/mod/github.com/projectdiscovery/retryablehttp-go@v1.0.17/request.go:97 +0x66
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc005e2d500, 0xc0135bba00, 0xc01bdc88c0, 0xc0135bba00?, 0x0, 0xc007507a78, 0xc00d202090?)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/http/request.go:639 +0x18cd
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc006280000, 0x22e80}, 0x1?, 0x0?)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/http/request.go:379 +0x5bb
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc005e2d500, 0xc0135bba00, 0xc00310efc0, 0xc00310eff0, 0xc00310f200)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/http/request.go:438 +0x36a
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc005e9a9a0, 0xc0135bb9a0)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x761c86?, 0x0?, 0xc00ebb6c60)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/core/executors.go:105 +0x4f8
```

**Comment by ehsandeep** [comment]
Fixed with https://github.com/projectdiscovery/utils/pull/176, will be part of the next nuclei release.
