### ISSUE TITLE
Proxying the internal requests for the GitHub integration is not working

### ISSUE THREAD

**Issue by forgedhallpass** [projectdiscovery/nuclei#3847]
Stack trace:
```
panic: interface conversion: http.RoundTripper is *oauth2.Transport, not *http.Transport

goroutine 1 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/reporting/trackers/github.New(0x140000ef1f0)
        /work/projects/projectdiscovery/nuclei/v2/pkg/reporting/trackers/github/github.go:61 +0x2d0
github.com/projectdiscovery/nuclei/v2/pkg/reporting.New(0x14000b7a540, {0x0, 0x0})
        /work/projects/projectdiscovery/nuclei/v2/pkg/reporting/reporting.go:102 +0x94
github.com/projectdiscovery/nuclei/v2/internal/runner.New(0x103aeb200)
        /work/projects/projectdiscovery/nuclei/v2/internal/runner/runner.go:183 +0x700
main.main()
        /work/projects/projectdiscovery/nuclei/v2/cmd/nuclei/main.go:74 +0x298
```

Cause: 
https://github.com/projectdiscovery/nuclei/blob/fc27fc94a5bb2678deb3588d041926ff8f1ab890/v2/pkg/reporting/trackers/github/github.go#L60

**Comment by dogancanbakir** [comment]
I'm closing this issue due to inactivity. If you believe this was a mistake, please feel free to reopen it.
