### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by mastercho** [projectdiscovery/nuclei#3855]
### Current Behavior:
While running big lists for, ofter like about a month long im ending up mostly with following error 

```
panic: runtime error: slice bounds out of range [11770:0]

goroutine 1504667829 [running]:
bytes.(*Buffer).grow(0xc092a1c0f0, 0x25bf4)
        /usr/local/go/src/bytes/buffer.go:142 +0x1f5
bytes.(*Buffer).Write(0xc092a1c0f0, {0xc056388000, 0x25bf4, 0x40dc01?})
        /usr/local/go/src/bytes/buffer.go:170 +0x66
bytes.(*Buffer).WriteTo(0xc092a1c120, {0x288a8e0?, 0xc092a1c0f0?})
        /usr/local/go/src/bytes/buffer.go:252 +0x83
io.copyBuffer({0x288a8e0, 0xc092a1c0f0}, {0x288a8c0, 0xc092a1c120}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:409 +0x16e
io.Copy(...)
        /usr/local/go/src/io/io.go:386
github.com/projectdiscovery/utils/reader.ReusableReadCloser.reset({0xc01fef5200, {0x288f320, 0xc097ab79a0}, 0xc092a1c0f0, 0xc092a1c120})
        /root/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.34/reader/reusable_read_closer.go:95 +0xa8
github.com/projectdiscovery/utils/reader.ReusableReadCloser.Read({0xc01fef5200, {0x288f320, 0xc097ab79a0}, 0xc092a1c0f0, 0xc092a1c120}, {0xc0a5b70000?, 0xc07f8768a0?, 0x477fee?})
        /root/go/pkg/mod/github.com/projectdiscovery/utils@v0.0.34/reader/reusable_read_closer.go:86 +0xb3
io.discard.ReadFrom({}, {0x288e480, 0xc092a1c150})
        /usr/local/go/src/io/io.go:651 +0x72
io.copyBuffer({0x28918e0, 0x3815240}, {0x288e480, 0xc092a1c150}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:413 +0x14b
io.Copy(...)
        /usr/local/go/src/io/io.go:386
github.com/projectdiscovery/retryablehttp-go.getLength({0x288e480?, 0xc092a1c150?})
        /root/go/pkg/mod/github.com/projectdiscovery/retryablehttp-go@v1.0.17/util.go:27 +0x45
github.com/projectdiscovery/retryablehttp-go.(*Request).Dump(0x465af1?)
        /root/go/pkg/mod/github.com/projectdiscovery/retryablehttp-go@v1.0.17/request.go:146 +0x65
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.dump(0xc0ab8cc980?, {0xc0a605f040?, 0x0?})
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/http/utils.go:117 +0x1b9
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc00920dc00, 0xc04451a9c0, 0xc034f8ed20, 0xc04451a9c0?, 0x0, 0xc07f877a78, 0xc0c3c27ad0?)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/http/request.go:582 +0x10c8
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc0095ee000, 0x22e80}, 0xc02212e480?, 0xc023eadbc8?)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/http/request.go:379 +0x5bb
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc00920dc00, 0xc04451a9c0, 0xc02212e000, 0xc02212e0f0, 0xc02212e540)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/http/request.go:438 +0x36a
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/executer.(*Executer).Execute(0xc007755a60, 0xc04451a960)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/protocols/common/executer/executer.go:81 +0x383
github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x7571e6?, 0x0?, 0xc0836cd040)
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/core/executors.go:128 +0x296
created by github.com/projectdiscovery/nuclei/v2/pkg/core.(*Engine).executeTemplateWithTargets.func2
        /root/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.6/pkg/core/executors.go:105 +0x4f8

```
### Expected Behavior:
To finish a scan without error

### Steps To Reproduce:
List contains 140k targets

and used `cat 140k.txt | nuclei  -stats -t cves,exposures,network,default-logins,vulnerabilities,exposed-panels,file -o sites.nuclei -rl 100 -c 10` to fire nuclei

### Anything else:
Unfortunately issue happens on random bases and can't give exactly steps to reproduce but i encounter it more often on big lists

**Comment by Mzack9999** [comment]
@mastercho This looks like a duplicate of https://github.com/projectdiscovery/nuclei/issues/3797 - It should be fixed in next release (and already in `dev` branch) with https://github.com/projectdiscovery/utils/pull/176
