### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by j4vaovo** [projectdiscovery/nuclei#4168]
version： v2.9.15
````
panic: tls: LoadSessionCoordinator.onEnterLoadSessionCheck failed: session is set and locked, no call to loadSession is allowed

goroutine 6384214 [running]:
github.com/refraction-networking/utls.uAssert(...)
        /root/go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/u_common.go:766
github.com/refraction-networking/utls.(*sessionController).onEnterLoadSessionCheck(...)
        /root/go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/u_session_controller.go:306
github.com/refraction-networking/utls.(*Conn).loadSession(0xc00bb38400, 0xc008ccf8c0)
        /root/go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/handshake_client.go:317 +0x165f
github.com/refraction-networking/utls.(*Conn).clientHandshake(0xc00bb38400, {0x2c1e870?, 0xc0000440d0})
        /root/go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/handshake_client.go:210 +0x11c
github.com/refraction-networking/utls.(*Conn).handleRenegotiation(0xc00bb38400)
        /root/go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/conn.go:1286 +0x167
github.com/refraction-networking/utls.(*Conn).handlePostHandshakeMessage(0xc00bb38400?)
        /root/go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/conn.go:1296 +0x24d
github.com/refraction-networking/utls.(*Conn).Read(0xc00bb38400, {0xc0071f2000, 0x1000, 0x2c0cbe0?})
        /root/go/pkg/mod/github.com/refraction-networking/utls@v1.5.2/conn.go:1384 +0x36e
net/http.(*persistConn).Read(0xc008f3d440, {0xc0071f2000?, 0x407986?, 0x60?})
        /usr/local/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc0059ece40)
        /usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc0059ece40, 0x1)
        /usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc008f3d440)
        /usr/local/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1765 +0x16ea
````

**Comment by MetzinAround** [comment]
Hi @j4vaovo , could you show us the command you ran before the crash? Any other information about what templates you might have been using or other info will help as wel.

**Comment by MetzinAround** [comment]
Thanks for the run command, @j4vaovo. The Open Source Team is going to be working on this now and will get back once they've got some news.

**Comment by dogancanbakir** [comment]
@j4vaovo,
I couldn't reproduce the issue even after updating dependencies. Please test the changes and let us know if the issue persists.

```console
git clone 
git checkout possible_fix_4168
cd cmd nuclei/v2/cmd/nuclei
go run . -l /opt/assets/webs.txt -tags druid,springboot,nacos -timeout 10 -bs 100 -c 10 -rl 150 -mhe 10 -tlsi -o /opt/assets/nuclei-all.txt -stats
```

**Comment by dogancanbakir** [comment]
Depends on #191 -possible fix in the latest version of utls /shrug

**Comment by dogancanbakir** [comment]
@j4vaovo,
Thank you for your feedback. I understand that you're having an issue and I'll do my best to resolve it. To start with, I'll update the dependencies that could be causing this problem and check if it fixes the issue. I know it's not easy to reproduce the problem, but please keep us posted if you face the same issue again. Thanks!
