### ISSUE TITLE
Nuclei crashes on -m

### ISSUE THREAD

**Issue by mikedesu** [projectdiscovery/nuclei#4171]
### Nuclei version:

[INF] Nuclei Engine Version: v2.9.15

### Current Behavior:

Attempting to run with -m causes crash

### Expected Behavior:

No crashing

### Steps To Reproduce:

run nuclei like:

```
head -n 1 root-domains | nuclei -nmhe -m -o nuclei.txt
```

### Anything else:

```
head -n 1 root-domains | nuclei -nmhe -m -o nuclei.txt 

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.9.15

                projectdiscovery.io

[INF] Current nuclei version: v2.9.15 (latest)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 6898
[INF] Targets loaded for current scan: 1
[INF] Running httpx on input host
[INF] Found 1 URL from httpx
[INF] Templates clustered: 1198 (Reduced 1137 Requests)
panic: http: multiple registrations for /metrics

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x3c013e0, {0x21e0bd4, 0x8}, {0x2b30140?, 0xc00c30edb0})
        /usr/local/go/src/net/http/server.go:2530 +0x219
net/http.(*ServeMux).HandleFunc(...)
        /usr/local/go/src/net/http/server.go:2567
net/http.HandleFunc(...)
        /usr/local/go/src/net/http/server.go:2579
github.com/projectdiscovery/clistats.(*Statistics).Start(0xc0009830c0)
        /home/darkmage/go/pkg/mod/github.com/projectdiscovery/clistats@v0.0.19/clistats.go:123 +0x8e
github.com/projectdiscovery/nuclei/v2/pkg/progress.(*StatsTicker).Init(0xc0007bcc90, 0x22a1e1d?, 0x0?, 0xc00aef2ee0?)
        /home/darkmage/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.15/pkg/progress/progress.go:109 +0x21a
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).executeTemplatesInput(0xc000000c00, 0xc00079eab0, 0xc000a6b340)
        /home/darkmage/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.15/internal/runner/runner.go:719 +0x3f4
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).runStandardEnumeration(_, {{0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {{0x0, 0x0}}, {{0x0, ...}}, ...}, ...}, ...)
        /home/darkmage/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.15/internal/runner/enumerate.go:34 +0x66
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration(0xc000000c00)
        /home/darkmage/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.15/internal/runner/runner.go:605 +0x16e8
main.main()
        /home/darkmage/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.9.15/cmd/nuclei/main.go:103 +0x4f2
```

**Comment by MetzinAround** [comment]
You might need to use `-mp` with `-m` in order to pick the port nuclei metrics are exposed on.

**Comment by tarunKoyalwar** [comment]
@mikedesu this issue is fixed now in nuclei v3.x . earlier there was collision when using `-m` without `-mp` but its resolved in latest release now
