### ISSUE TITLE
[issue]  panic: runtime error: invalid memory address or nil pointer dereference (random-agent)

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#455]
**Describe the bug**
We're encountering a SIGSEGV crash whilst attempting to scan a small group of hosts.

**Command line**
```
subfinder -d "$1" | httpx -csp-probe -threads 1500 -ports 80,88,443,8000,8080,8443,10443 \
| nuclei -random-agent -retries 0 -bulk-size 2500 -timeout 10 -stats \
-t /root/nuclei-templates/cves \
-t /root/nuclei-templates/dns/spoofable-spf-records-ptr.yaml \
-t /root/nuclei-templates/files/apc-info.yaml \
-t /root/nuclei-templates/files/elasticsearch.yaml \
-t /root/nuclei-templates/files/error-logs.yaml \
-t /root/nuclei-templates/files/git-config.yaml \
-t /root/nuclei-templates/files/jkstatus-manager.yaml \
-t /root/nuclei-templates/files/laravel-env.yaml \
-t /root/nuclei-templates/files/magento-config.yaml \
-t /root/nuclei-templates/files/php-errors.yaml \
-t /root/nuclei-templates/files/phpinfo.yaml \
-t /root/nuclei-templates/files/public-tomcat-instance.yaml \
-t /root/nuclei-templates/files/server-private-keys.yaml \
-t /root/nuclei-templates/files/server-status-localhost.yaml \
-t /root/nuclei-templates/files/shell-history.yaml \
-t /root/nuclei-templates/files/sql-dump.yaml \
-t /root/nuclei-templates/files/wordpress-db-backup.yaml \
-t /root/nuclei-templates/files/wordpress-debug-log.yaml \
-t /root/nuclei-templates/files/wordpress-directory-listing.yaml \
-t /root/nuclei-templates/files/wordpress-emergency-script.yaml \
-t /root/nuclei-templates/files/zip-backup-files.yaml \
-t /root/nuclei-templates/fuzzing/arbitrary-file-read.yaml \
-t /root/nuclei-templates/fuzzing/directory-traversal.yaml \
-t /root/nuclei-templates/fuzzing/generic-lfi-fuzzing.yaml \
-t /root/nuclei-templates/misc/dir-listing.yaml \
-t /root/nuclei-templates/misc/security.txt.yaml \
-t /root/nuclei-templates/panels \
-t /root/nuclei-templates/security-misconfiguration \
-t /root/nuclei-templates/technologies/basic-auth-detection.yaml \
-t /root/nuclei-templates/technologies/prometheus-exposed-panel.yaml \
-t /root/nuclei-templates/technologies/terraform-detect.yaml \
-t /root/nuclei-templates/technologies/prometheus-exporter-detect.yaml \
-t /root/nuclei-templates/technologies/redmine-cli-detect.yaml \
-t /root/nuclei-templates/tokens \
-t /root/nuclei-templates/vulnerabilities \
-exclude /root/nuclei-templates/panels/swagger-panel.yaml
```

**Nuclei version**
`2.2.1-dev built from c07771`

**Screenshot of the error or bug**
![nuclei](https://user-images.githubusercontent.com/466878/102715521-f456f300-42cd-11eb-9767-abc5a18705db.png)

**Comment by bauthard** [comment]
Reproduced this with and without stats flag.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1003eee]

goroutine 973164 [running]:
strings.IndexByte(...)
	/usr/local/opt/go/libexec/src/strings/strings.go:114
strings.Index(0x0, 0x9a, 0x185528c, 0x1, 0x271c9c00c92ad20d)
	/usr/local/opt/go/libexec/src/strings/strings.go:1030 +0x63b
strings.genSplit(0x0, 0x9a, 0x185528c, 0x1, 0x0, 0x1, 0x73, 0x2, 0x2)
	/usr/local/opt/go/libexec/src/strings/strings.go:251 +0xff
strings.SplitN(...)
	/usr/local/opt/go/libexec/src/strings/strings.go:273
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).setCustomHeaders(0xc001170960, 0xc01cf2c9c0)
	/Users/bauthard/Github/nuclei/v2/pkg/executer/executer_http.go:751 +0xae
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).handleHTTP(0xc001170960, 0xc016c7e840, 0x16, 0xc01cf2c9c0, 0xc006fc9db8, 0xc01f267d00, 0xc00fa40870, 0xc006fc9d28, 0x4, 0xc01a617900, ...)
	/Users/bauthard/Github/nuclei/v2/pkg/exec:439 +0x5d
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).ExecuteHTTP(0xc001170960, 0xc0002614d0, 0xc016c7e840, 0x16, 0xa)
	/Users/bauthard/Github/nuclei/v2/pkg/executer/executer_http.go:407 +0x76f
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1.1(0xc00415d4a0, 0xc001170960, 0xc0002614d0, 0xc0257410a0, 0x0, 0xc0001d4100, 0xc0011444e0, 0xc016c7e840, 0x16)
	/Users/bauthard/Github/nuclei/v2/internal/runner/processor.go:106 +0x217
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1
	/Users/bauthard/Github/nuclei/v2/internal/runner/processor.go:100 +0x15a
```

**Comment by abdulsec** [comment]
i have got the same error

**Comment by bauthard** [comment]
Hi @abdulsec, it's a known bug that we already fixed in the dev branch with `random-agent` flag, for now, you can avoid using this flag to avoid this error.

**Comment by abdulsec** [comment]
if i add the -silent  in nuclei ,it hide the error , i hope this help

**Comment by geeknik** [comment]
Thanks @abdulsec. I added the `-silent` flag, however it did not fix this issue on my end. 

```
# nuclei -random-agent -silent -retries 0 -bulk-size 2500 -timeout 5 -stats -t templates/
**SNIP**
[0:51:25] | Templates: 393 | Hosts: 1628 | RPS: 153 | Errors: 298611 | Requests: 473536/1720796 (27%)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4038ae]
```

Nuclei 2.2.1-dev with go version go1.15.6 linux/amd64 on Ubuntu 20.04.1 LTS.
