### ISSUE TITLE
go-smb2 dependency panic when running smb templates

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/nuclei#4687]
### Nuclei version:

dev | main

### Current Behavior:

```console
 cmdutil ./nuclei -uc -ul 1000 -pt javascript -stats                                                              

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.8-dev

		projectdiscovery.io

[INF] Running uncover queries from template against: shodan
[INF] Current nuclei version: v3.1.8-dev (development)
[INF] Current nuclei-templates version: v9.7.4 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 6
[INF] Templates loaded for current scan: 23
[INF] Executing 23 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 626
panic: runtime error: slice bounds out of range [:285216000] with capacity 338

goroutine 1864 [running]:
github.com/hirochachacha/go-smb2.(*conn).runReciever(0x1400cbed380)
	/Users/tarun/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.1.0/conn.go:557 +0x6cc
created by github.com/hirochachacha/go-smb2.(*Negotiator).negotiate in goroutine 494
	/Users/tarun/go/pkg/mod/github.com/hirochachacha/go-smb2@v1.1.0/conn.go:102 +0x1e8

```

### Expected Behavior:

```console
 cmdutil ./nuclei -uc -ul 1000 -pt javascript -stats                                          

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.8-dev

		projectdiscovery.io

[INF] Running uncover queries from template against: shodan
[INF] Current nuclei version: v3.1.8-dev (development)
[INF] Current nuclei-templates version: v9.7.4 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 6
[INF] Templates loaded for current scan: 23
[INF] Executing 23 signed templates from projectdiscovery/nuclei-templates
[INF] Targets loaded for current scan: 626

**Comment by mastercho** [comment]
![f55d5e0bd62c392a40e6ec104208ebaa](https://github.com/projectdiscovery/nuclei/assets/10222100/3c0bd1bc-29f7-432d-bfe5-5aa55516cbd5)

Can confirm the issue
