### ISSUE TITLE
Nuclei Stop after a while 

### ISSUE THREAD

**Issue by dragonked2** [projectdiscovery/nuclei#4758]
Last Version show this error and keep flooding errors

runtime: failed to create new OS thread (have 497 already; errno=8)
fatal error: runtime.newosproc

runtime stack:
runtime.throw({0x228506e, 0x11})
        runtime/panic.go:1077 +0x4d fp=0x4b5fcd4 sp=0x4b5fcc0 pc=0x601dd
runtime.newosproc(0x295b7200)
        runtime/os_windows.go:890 +0x12c fp=0x4b5fd04 sp=0x4b5fcd4 pc=0x5c8dc
runtime.newm1(0x295b7200)
        runtime/proc.go:2455 +0xaf fp=0x4b5fd20 sp=0x4b5fd04 pc=0x66dcf
runtime.newm(0x0, 0xd453300, 0x1f0)
        runtime/proc.go:2430 +0x131 fp=0x4b5fd3c sp=0x4b5fd20 pc=0x66cc1
runtime.startm(0xd453300, 0x0, 0x0)
        runtime/proc.go:2624 +0x1c3 fp=0x4b5fd68 sp=0x4b5fd3c pc=0x67323
runtime.handoffp(0xd453300)
        runtime/proc.go:2665 +0x354 fp=0x4b5fd90 sp=0x4b5fd68 pc=0x67774
runtime.retake(0x7a01e6052adc)
        runtime/proc.go:5731 +0x22e fp=0x4b5fdc8 sp=0x4b5fd90 pc=0x6ed6e
runtime.sysmon()
        runtime/proc.go:5639 +0x4cf fp=0x4b5fe38 sp=0x4b5fdc8 pc=0x6e91f
runtime.mstart1()
        runtime/proc.go:1600 +0x7a fp=0x4b5fe48 sp=0x4b5fe38 pc=0x65b1a
runtime.mstart0()
        runtime/proc.go:1557 +0x4f fp=0x4b5fe54 sp=0x4b5fe48 pc=0x65a8f
runtime.mstart()
        runtime/asm_386.s:275 +0x5 fp=0x4b5fe58 sp=0x4b5fe54 pc=0x94515

goroutine 1 [select, 1 minutes]:
runtime.gopark(0x282243c, 0x0, 0x9, 0x18, 0x1)
        runtime/proc.go:398 +0xfd fp=0x1cfd5310 sp=0x1cfd52fc pc=0x6330d
runtime.selectgo(0x1cfd5418, 0x1cfd5410, 0x0, 0x1, 0x1, 0x1)
        runtime/select.go:327 +0xac8 fp=0x1cfd53f0 sp=0x1cfd5310 pc=0x74598
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).AddWithContext(0x14a4efa8, {0x2b8d698, 0x3fce2c0})
        github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:63 +0x93 fp=0x1cfd542c sp=0x1cfd53f0 pc=0xe72183
github.com/remeh/sizedwaitgroup.(*SizedWaitGroup).Add(...)
        github.com/remeh/sizedwaitgroup@v1.0.0/sizedwaitgroup.go:51
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateSpray(0xda9c360, {0x17c45500, 0x150d, 0x1540}, {0x2b8a8f4, 0xdc56280})
        github.com/projectdiscovery/nuclei/v3/pkg/core/execute_options.go:120 +0xb7 fp=0x1cfd545c sp=0x1cfd542c pc=0x1c57987
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).ExecuteScanWithOpts(0xda9c360, {0x1484a000, 0x1d1f, 0x2000}, {0x2b8a8f4, 0xdc56280}, 0x0)
        github.com/projectdiscovery/nuclei/v3/pkg/core/execute_options.go:91 +0x83d fp=0x1cfd56f4 sp=0x1cfd545c pc=0x1c5786d
github.com/projectdiscovery/nuclei/v3/internal/runner.(*Runner).executeTemplatesInput(0xde100c0, 0xdc579f0, 0xda9c360)
        github.com/projectdiscovery/nuclei/v3/internal/runner/runner.go:578 +0x21e fp=0x1cfd574c sp=0x1cfd56f4 pc=0x1c7b38e
github.com/projectdiscovery/nuclei/v3/internal/runner.(*Runner).runStandardEnumeration(0xde100c0, {{0x0, 0x0}, {0x0, 0x0}, {{0x0, 0x0}, {{0x0, 0x0}}, {{0x0, ...}}, ...}, ...}, ...)
        github.com/projectdiscovery/nuclei/v3/internal/runner/runner.go:326 +0xb9 fp=0x1cfd5864 sp=0x1cfd574c pc=0x1c793b9
github.com/projectdiscovery/nuclei/v3/internal/runner.(*Runner).RunEnumeration(0xde100c0)
        github.com/projectdiscovery/nuclei/v3/internal/runner/runner.go:498 +0x111c fp=0x1cfd5ecc sp=0x1cfd5864 pc=0x1c7abbc
main.main()
        ./main.go:165 +0x6e3 fp=0x1cfd5fa4 sp=0x1cfd5ecc pc=0x1c7f983
runtime.main()
        runtime/proc.go:267 +0x2b7 fp=0x1cfd5ff0 sp=0x1cfd5fa4 pc=0x62e77
runtime.goexit()
        runtime/asm_386.s:1363 +0x1 fp=0x1cfd5ff4 sp=0x1cfd5ff0 pc=0x95a21

goroutine 2 [force gc (idle), 52 minutes]:

**Comment by tarunKoyalwar** [comment]
@dragonked2 , thanks for reporting this but gopark errors like ^ are caused due to setting high concurrency which seems to be the case or system not supporting more threads due to some reason 

> runtime: failed to create new OS thread (have 497 already; errno=8)

reducing concurrency should fix this if it is related to nuclei , here's our guide to setting concurrency and other options https://docs.projectdiscovery.io/tools/nuclei/mass-scanning-cli
