### ISSUE TITLE
[Bug]   invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by savushkin-yauheni** [projectdiscovery/nuclei#477]
Hi guys!

**Nuclei version**

2.2.0

**Nuclei template version**

{"templates-directory":"/root/nuclei-templates","current-version":"7.3.7","last-checked":"2021-01-12T08:34:35.595424475Z"}

**Describe the bug**
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9889f7]

goroutine 23 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/executer.(*HTTPExecuter).ExecuteHTTP(0xc000e32b40, 0xc0000a6060, 0xc00014b6c0, 0x1a, 0xc000fc4900)
        /home/marco/go/src/github.com/projectdiscovery/nuclei/v2/pkg/executer/executer_http.go:359 +0x5a7
github.com/projectdiscovery/nuclei/v2/pkg/workflows.(*NucleiVar).Call(0xc00106a500, 0x0, 0x0, 0x0, 0xc001260028, 0x0, 0x7ff, 0x0)
        /home/marco/go/src/github.com/projectdiscovery/nuclei/v2/pkg/workflows/var.go:89 +0x6bf
github.com/d5/tengo.(*VM).run(0xc001260000)
        /home/marco/go/src/github.com/d5/tengo/vm.go:633 +0x3326
github.com/d5/tengo.(*VM).Run(0xc001260000, 0xc000584000, 0xe3)
        /home/marco/go/src/github.com/d5/tengo/vm.go:77 +0xcf
github.com/d5/tengo.(*Compiled).RunContext.func1(0xc00125fc80, 0xc001260000)
        /home/marco/go/src/github.com/d5/tengo/script.go:222 +0x2b
created by github.com/d5/tengo.(*Compiled).RunContext
        /home/marco/go/src/github.com/d5/tengo/script.go:221 +0x22d

```

**Commands to reproduce**

```
nuclei  -target https://blog.olamoney.com/ -t workflows/wordpress-workflow.yaml
```

Thanks!

**Comment by geeknik** [comment]
> @geeknik for the `-dev` version it's expected, we have removed the support of tengo in the dev version, if you using dev version with old templates that works based on tengo, this error is expected.

How do I differentiate between a template that requires tengo and a template that does not so I stop seeing this error with the dev version? Thank you.

**Comment by bauthard** [comment]
@savushkin-yauheni should be fixed if you update the templates to the latest version https://github.com/projectdiscovery/nuclei-templates/releases/tag/v8.0.4
