### ISSUE TITLE
Error while starting using interactsh server

### ISSUE THREAD

**Issue by MridulVohra** [projectdiscovery/nuclei#4895]
When start using Interactsh Server: oast.me
an error pops up:

```bash
panic: assignment to entry in nil map

goroutine 243436 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute.func1(0xc0167b5a90)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/templates/cluster.go:257 +0x1a6
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1.1(0xc0167b5a90)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/protocols/http/request.go:436 +0x435
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).executeRequest(0xc01164b4a0, 0xc01234a990, 0xc00ec6fae0, 0xc007320c90, 0x0, 0xc008699b18, 0x0?)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/protocols/http/request.go:706 +0x3562
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults.func1({0xc00e34d500, 0x1c}, 0x7f4f28685bc8?, 0x41f656?)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/protocols/http/request.go:409 +0x56b
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http.(*Request).ExecuteWithResults(0xc01164b4a0, 0xc01234a990, 0xc007320cc0, 0xc007320c90, 0xc01234a9a8)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/protocols/http/request.go:473 +0x36a
github.com/projectdiscovery/nuclei/v3/pkg/templates.(*ClusterExecuter).Execute(0xc0049b5340, 0xc012024000)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/templates/cluster.go:254 +0x14a
github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2.1(0x7c5405?, 0x0?, 0xc01111d100)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/core/executors.go:132 +0x1d8
created by github.com/projectdiscovery/nuclei/v3/pkg/core.(*Engine).executeTemplateWithTargets.func2 in goroutine 243434
        /home/kali/go/pkg/mod/github.com/projectdiscovery/nuclei/v3@v3.2.1/pkg/core/executors.go:108 +0x459
```

**Comment by zeandrade** [comment]
Hi, same error  as @MridulVohra reported. Downgraded to v.3.1.10  to keep working.

**Comment by tarunKoyalwar** [comment]
@zeandrade  @MridulVohra , i couldn't reproduce this looks like it only happens in some cases , regardless https://github.com/projectdiscovery/nuclei/pull/4896 should fix the issue , can you confirm if issue is resolved ?
temporarily you can install from linked branch using

```console
go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@f460135
```

**Comment by 0xElmalky** [comment]
not resolved i had same issue

**Comment by graysoncorrea** [comment]
> Não resolvido eu tinha o mesmo problema



> not resolved i had same issue

y too

**Comment by 2u1fuk4r** [comment]
> @zeandrade @MridulVohra , ~i couldn't reproduce this looks like it only happens in some cases~, regardless #4896 should fix the issue , can you confirm if issue is resolved ? temporarily you can install from linked branch using
> 
> ```
> go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@issue-4895-panic
> ```

thank yoou so much it is work for me date:16.03.2024 thank you so much again :)

**Comment by graysoncorrea** [comment]
@2u1fuk4r For me it's working, without .

**Comment by MridulVohra** [comment]
@tarunKoyalwar  the nuclei is working completely fine.
Thanks :)
