### ISSUE TITLE
Nuclei Automatic Scan Showing Error with Update Flag Issue | Kali Linux

### ISSUE THREAD

**Issue by Th3BlackHol3** [projectdiscovery/nuclei#5131]
### Nuclei version: 
**v3.2.4**

### Current Behavior:
Hi,
Recently, I have installed Kali Linux and installed Nuclei from the package manager. After that, Firstly, I tried to run a nuclei automatic scan ``` nuclei -u target.com -as ``` but nuclei gave Me a panic runtime error. I am giving the error below.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d0bcfb]

goroutine 4627 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/tmplexec.(*TemplateExecuter).ExecuteWithResults(0xc0160d9e40?, 0xc0139399a0)
	/build/nuclei-7vt4Mn/nuclei-3.2.4/pkg/tmplexec/exec.go:181 +0x1b
github.com/projectdiscovery/nuclei/v3/pkg/protocols/common/automaticscan.(*Service).getTagsUsingDetectionTemplates.func1(0xc005ffd088)
	/build/nuclei-7vt4Mn/nuclei-3.2.4/pkg/protocols/common/automaticscan/automaticscan.go:298 +0x186
created by github.com/projectdiscovery/nuclei/v3/pkg/protocols/common/automaticscan.(*Service).getTagsUsingDetectionTemplates in goroutine 201
	/build/nuclei-7vt4Mn/nuclei-3.2.4/pkg/protocols/common/automaticscan/automaticscan.go:254 +0x12c

```
After that I thought I should update Nuclei, Then I tried with ```nuclei -up``` and ```nuclei -update``` It showed Me ```flag provided but not defined: -up``` and ```flag provided but not defined: -update```. 

Lastly, I cloned the repository and tried with ```go build``` it also gave an error.  I have tested from My friend's Kali Environment and it was the same scenario.

* OS: Kali Linux 2024.1
* Kernel: 6.6.15-amd64
* Go Version: go1.22.2

### Expected Behavior:
Automated scans should run smoothly, -up / -update flags should update nuclei. 

Thanks!

**Comment by ehsandeep** [comment]
@Th3BlackHol3 this panic got fixed in latest version of nuclei, i.e 3.2.5 - https://github.com/projectdiscovery/nuclei/releases/tag/v3.2.5

about update option, if you are installing nuclei using kali package manager, it's patched version of nuclei, see https://github.com/projectdiscovery/nuclei/discussions/2151 for details.
