### ISSUE TITLE
Nuclei v3.2.9 (latest) crashes when supplied with a large text file

### ISSUE THREAD

**Issue by mailler0xa** [projectdiscovery/nuclei#5348]
### Nuclei version:
v3.2.9

### Current Behavior:
Crashes with such an error (can't get it all to be saved to a file)
Sample error message:
`goroutine 7432 [runnable]:
github.com/projectdiscovery/nuclei/v3/pkg/catalog/loader.(*Store).LoadTemplatesWithTags.func4()
        github.com/projectdiscovery/nuclei/v3/pkg/catalog/loader/loader.go:450 fp=0xc002845fe0 sp=0xc002845fd8 pc=0x1f57300
runtime.goexit()
        runtime/asm_amd64.s:1650 +0x1 fp=0xc002845fe8 sp=0xc002845fe0 pc=0x471301
created by github.com/projectdiscovery/nuclei/v3/pkg/catalog/loader.(*Store).LoadTemplatesWithTags in goroutine 1
        github.com/projectdiscovery/nuclei/v3/pkg/catalog/loader/loader.go:450 +0x2bb
`
[check the attached file for most of the error text that I could copy].

[file.txt](https://github.com/user-attachments/files/16067401/file.txt)

### Expected Behavior:
It should run normally as seen in previous versions.

### Anything else:
It's not reproducible in the previous nuclei version.

**Comment by web1919** [comment]
同问

**Comment by dwisiswant0** [comment]
I don’t think this issue is relevant anymore, so I’ll close it. Feel free to reopen if I’m mistaken.
