### ISSUE TITLE
Nuclei crashes with -nmhe flag

### ISSUE THREAD

**Issue by geeknik** [projectdiscovery/nuclei#5442]
### Nuclei version:
3.2.x, 3.3.0

### Current Behavior:
Crashes.
```
goroutine 47 [running]:
github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.glob..func1(0x0?)
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:124 +0x50
github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.(*Agent).monitorWorker(0x14000d68aa0, 0x1400065bce0)
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:90 +0xd4
github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.(*Agent).Start.func1()
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:62 +0xa0
created by github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor.(*Agent).Start in goroutine 1
	github.com/projectdiscovery/nuclei/v3/pkg/utils/monitor/monitor.go:56 +0xc4
```

### Expected Behavior:
No crash.

### Steps To Reproduce:
I can provide the command line privately via Discord.

### Anything else:
[nuclei-stacktrace-cqge0oqhc8a86rt7j9og.dump.gz](https://github.com/user-attachments/files/16362533/nuclei-stacktrace-cqge0oqhc8a86rt7j9og.dump.gz)
[nuclei-stacktrace-cqge15qhc8a8dtr5aa80.dump.gz](https://github.com/user-attachments/files/16362534/nuclei-stacktrace-cqge15qhc8a8dtr5aa80.dump.gz)

**Comment by dogancanbakir** [comment]
Could you send me the cmd? Thanks!

**Comment by dogancanbakir** [comment]
I couldn't replicate the issue - reached out over Discord. I assisted with debugging but didn't receive any further information. Closing this due to inactivity.
