### ISSUE TITLE
[BUG] ...sdk with proxy error

### ISSUE THREAD

**Issue by tongchengbin** [projectdiscovery/nuclei#5650]
`###` Is there an existing issue for this?

- [X] I have searched the existing `issues.`

### Current Behavior

```
func ExampleNucleiEngine() {
	// create nuclei engine with options
	ne, err := nuclei.NewNucleiEngine(
		nuclei.WithTemplateFilters(nuclei.TemplateFilters{IDs: []string{"self-signed-ssl"}}), // only run self-signed-ssl template
		nuclei.WithProxy([]string{"socks5://127.0.0.1:9000"}, false),
	)
	if err != nil {
		panic(err)
	}
	// load targets and optionally probe non http/https targets
	ne.LoadTargets([]string{"scanme.sh"}, false)
	// when callback is nil it nuclei will print JSON output to stdout
	err = ne.ExecuteWithCallback(nil)
	if err != nil {
		panic(err)
	}
	defer ne.Close()

	// Output:
	// [self-signed-ssl] scanme.sh:443
}


Error
=== RUN   ExampleNucleiEngine
--- FAIL: ExampleNucleiEngine (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x14 pc=0x19dec36]

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc001007bb0, {0x0, 0x0}, 0x206592e3348?, 0x0, {0x1f368c0, 0x3ffe7a0})
	D:/Program/go/src/testing/example.go:91 +0x645
testing.runExample.func2()
	D:/Program/go/src/testing/run_example.go:59 +0x116
panic({0x1f368c0?, 0x3ffe7a0?})
	D:/Program/go/src/runtime/panic.go:770 +0x132
github.com/projectdiscovery/utils/maps.(*SyncLockMap[...]).Get(0xc000dca030?, {0xc0009061a0?, 0x0?})
	C:/Users/tongc/go/pkg/mod/github.com/projectdiscovery/utils@v0.2.7/maps/synclock_map.go:71 +0x36
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/httpclientpool.wrappedGet(0xc000c00808, 0xc001006d38)
	D:/code/github.com/nuclei/pkg/protocols/http/httpclientpool/clientpool.go:179 +0x65
github.com/projectdiscovery/nuclei/v3/pkg/protocols/http/httpclientpool.Get(0xc000c00808?, 0x0?)
	D:/code/github.com/nuclei/pkg/protocols/http/httpclientpool/clientpool.go:171 +0x52
github.com/projectdiscovery/nuclei/v3/lib.(*NucleiEngine).init(0xc000df6708, {0x2a65a30, 0x417d380})
	D:/code/github.com/nuclei/lib/sdk_private.go:112 +0x105
github.com/projectdiscovery/nuclei/v3/lib.NewNucleiEngineCtx({0x2a65a30, 0x417d380}, {0xc000bbf960, 0x2, 0x10?})
	D:/code/github.com/nuclei/lib/sdk.go:285 +0x15a
github.com/projectdiscovery/nuclei/v3/lib.NewNucleiEngine(...)
	D:/code/github.com/nuclei/lib/sdk.go:293
github.com/projectdiscovery/nuclei/v3/lib_test.ExampleNucleiEngine()
	D:/code/github.com/nuclei/lib/example_test.go:17 +0x1b5
testing.runExample({{0x23ce559, 0x13}, 0x272f7d8, {0x2415fc1, 0x20}, 0x0})
	D:/Program/go/src/testing/run_example.go:63 +0x2de
testing.runExamples(0x2a7b200?, {0x403e300, 0x2, 0x0?})

	D:/Program/go/src/testing/example.go:40 +0x126
testing.(*M).Run(0xc000de2c80)
	D:/Program/go/src/testing/testing.go:2029 +0x75d
github.com/projectdiscovery/nuclei/v3/lib_test.TestMain(0xc000de2c80)
	D:/code/github.com/nuclei/lib/example_test.go:86 +0x55
main.main()
	_testmain.go:53 +0x195
```

### Expected Behavior

no error

### Steps To Reproduce

nuclei sdk example 

### Environment

```markdown
- OS: windows
- Nuclei:  v3.3.2
- Go: 1.22.7
```

**Comment by dogancanbakir** [comment]
Probably the same as https://github.com/projectdiscovery/nuclei/issues/5182. Fixed in https://github.com/projectdiscovery/nuclei/pull/5626. Could you retry with `dev` branch?
