### ISSUE TITLE
Do not clobber the "tcp" dialer for MySQL

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/nuclei#5854]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

-

### Expected Behavior

-

### Steps To Reproduce

-

### Relevant log output

```shell

```

### Environment

```markdown
- OS: 
- Nuclei: 
- Go:
```

**Comment by qiwentaidi** [comment]
<img width="849" alt="Image" src="https://github.com/user-attachments/assets/8733d78b-0714-45b8-9df7-f5c9fe25fa1c" />
When I use nucleus's SDK to call vulnerability scanning and then connect to the MySQL database, it will prompt a null pointer error. Upon checking the code, I found that nucleus rewrote the MySQL driver, which caused the error

**Comment by qiwentaidi** [comment]
> <img alt="Image" width="849" src="https://private-user-images.githubusercontent.com/104491549/400114585-8733d78b-0714-45b8-9df7-f5c9fe25fa1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NjU1NzIsIm5iZiI6MTczNTk2NTI3MiwicGF0aCI6Ii8xMDQ0OTE1NDkvNDAwMTE0NTg1LTg3MzNkNzhiLTA3MTQtNDViOC05ZGY3LWY1YzlmZTI1ZmExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQwNDM0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTliZTQyY2YwNzk5MjI3YWM0NzBhMDgyNDYyY2FhZjMzN2ViMGM4YTI3NWZmNDNiMTYwODBkY2EyNWQ2YjRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mJYxXWW-nlViPpYCVSalMqtQLdXeA8525oP19RurJAQ"> When I use nucleus's SDK to call vulnerability scanning and then connect to the MySQL database, it will prompt a null pointer error. Upon checking the code, I found that nucleus rewrote the MySQL driver, which caused the error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102500b30]

goroutine 6458 [running]:
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).dial(0x0, {0x107952820, 0x1400646afc0}, 0x14014440900)
        /Users/qwtd/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.2.9/fastdialer/dialer_private.go:66 +0x50
github.com/projectdiscovery/fastdialer/fastdialer.(*Dialer).Dial(0x0, {0x107952820, 0x1400646afc0}, {0x103e17267, 0x3}, {0x14009e8f9d0, 0x10})
        /Users/qwtd/go/pkg/mod/github.com/projectdiscovery/fastdialer@v0.2.9/fastdialer/dialer.go:198 +0x1e8
github.com/projectdiscovery/nuclei/v3/pkg/protocols/common/protocolstate.Init.func1({0x107952820, 0x1400646afc0}, {0x14009e8f9d0, 0x10})
        /Users/qwtd/Code/Slack/lib/nuclei/pkg/protocols/common/protocolstate/state.go:159 +0x64
github.com/go-sql-driver/mysql.(*connector).Connect(0x1400ae27080, {0x107952858, 0x1099e7180})
        /Users/qwtd/go/pkg/mod/github.com/go-sql-driver/mysql@v1.7.1/connector.go:46 +0x314
database/sql.(*DB).conn(0x1400cc96ea0, {0x107952858, 0x1099e7180}, 0x1)
        /usr/local/go/src/database/sql/sql.go:1423 +0x8a4
database/sql.(*DB).PingContext.func1(0x1)
        /usr/local/go/src/database/sql/sql.go:892 +0x68
database/sql.(*DB).retry(0x1400cc96ea0, 0x1401960e498)
        /usr/local/go/src/database/sql/sql.go:1568 +0x4c
database/sql.(*DB).PingContext(0x1400cc96ea0, {0x107952858, 0x1099e7180})
        /usr/local/go/src/database/sql/sql.go:891 +0x148
database/sql.(*DB).Ping(0x1400cc96ea0)
        /usr/local/go/src/database/sql/sql.go:909 +0x48
slack-wails/core/portscan.MysqlConn({0x1400ad98dd0, 0x10}, {0x14007d9ed48, 0x4}, {0x14007d9ed80, 0x6})
        /Users/qwtd/Code/Slack/core/portscan/mysql.go:50 +0x2dc
slack-wails/core/portscan.MysqlScan({0x107952778, 0x14005f61170}, {0x1400ad98dd0, 0x10}, {0x14002cd3c20, 0x2, 0x2}, {0x1400a20ed88, 0x47, 0x47})
        /Users/qwtd/Code/Slack/core/portscan/mysql.go:23 +0x164
slack-wails/core/portscan.PortBrute({0x107952778, 0x14005f61170}, {0x1400ad98dc8, 0x18}, {0x14002cd3c20, 0x2, 0x2}, {0x1400a20ed88, 0x47, 0x47})
        /Users/qwtd/Code/Slack/core/portscan/portbrute.go:63 +0xaa8
slack-wails/services.(*App).PortBrute(0x14005406af0, {0x1400ad98dc8, 0x18}, {0x14002cd3c20, 0x2, 0x2}, {0x1400a20ed88, 0x47, 0x47})
        /Users/qwtd/Code/Slack/services/app.go:411 +0x80
reflect.Value.call({0x1078af4a0, 0x14005406af0, 0x9613}, {0x103e1a0d5, 0x4}, {0x14002e9c9b0, 0x3, 0x3})
        /usr/local/go/src/reflect/value.go:581 +0xa00
reflect.Value.Call({0x1078af4a0, 0x14005406af0, 0x9613}, {0x14002e9c9b0, 0x3, 0x3})
        /usr/local/go/src/reflect/value.go:365 +0x74
github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call(0x1400542c3f0, {0x140137aa030, 0x3, 0x3})
        /Users/qwtd/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/binding/boundMethod.go:72 +0x31c
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage(0x14007ef5180, {0x1400d4a0a80, 0x36b}, {0x1079844c0, 0x14000485140})
        /Users/qwtd/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/frontend/dispatcher/calls.go:45 +0x430
github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage(0x14007ef5180, {0x1400d4a0a80, 0x36b}, {0x1079844c0, 0x14000485140})
        /Users/qwtd/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/frontend/dispatcher/dispatcher.go:42 +0x18c
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).processMessage.func1()
        /Users/qwtd/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/frontend/desktop/darwin/frontend.go:390 +0x70
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).processMessage in goroutine 26

**Comment by dogancanbakir** [comment]
@qiwentaidi Can you create a new issue and tag me? Thank you!
