### ISSUE TITLE
[issue] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/nuclei#633]
**Nuclei version**
2.3.1

Repeat the following command a few times:- 

`echo 34.232.227.185 | nuclei -t dns/ec2-detection.yaml `

**Screenshot of the error or bug**

<details>
<summary>Crash</summary>

```
echo 34.232.227.185 | nuclei -t ec2-detection.yaml 

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.3.1

		projectdiscovery.io

[INF] Loading templates...
[INF] [ec2-detection] Amazon EC2 detection (@melbadry9) [info]
[INF] Loading workflows...
[INF] Using 1 rules (1 templates, 0 workflows)
[0:00:00] | Templates: 1 | Hosts: 1 | RPS: 5572 | Matched: 0 | Errors: 1 | Requests: 1/1 (100%)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1010e0668]

goroutine 1 [running]:
github.com/projectdiscovery/clistats.(*Statistics).Stop(0x140000122d0, 0x140000122d0, 0x0)
	/Users/geekboy/go/pkg/mod/github.com/projectdiscovery/clistats@v0.0.7/clistats.go:170 +0x38
github.com/projectdiscovery/nuclei/v2/pkg/progress.(*StatsTicker).Stop(0x1400011da40)
	/Users/geekboy/Github/nuclei/v2/pkg/progress/progress.go:219 +0x90
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).RunEnumeration(0x14000176000)
	/Users/geekboy/Github/nuclei/v2/internal/runner/runner.go:325 +0xaf8
main.main()
	/Users/geekboy/Github/nuclei/v2/cmd/nuclei/main.go:28 +0x68

```
</details>

**Comment by geeknik** [comment]
Using nuclei 2.3.1 built from 5cd493 with go version go1.16 linux/amd64 and Ubuntu 20.04.2 LTS, I am unable to confirm a crash.

**Comment by ehsandeep** [comment]
@geeknik looks like this is only reproducible on Mac.
