### ISSUE TITLE
[issue] Segmentation fault on Mac M1

### ISSUE THREAD

**Issue by k1000o23** [projectdiscovery/nuclei#642]
**Describe the bug**
This bug did not occur with previous versions of nuclei. It could run a large number of hosts with templates (around 90k hosts and 500 templates). Now when I run it in the terminal after a few minutes I get this error. If I run nuclei again it exits instantly, as if there was a bug that doesn't even let it start.

Thank you very much team for all you do!

**Nuclei version**
2.3.2

**Screenshot of the error or bug**
```
`unexpected fault address 0x174656e2e7287ba
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x174656e2e7287ba pc=0x1046aa3d0]`

`goroutine 65 [running]:
runtime.throw(0x1049793b4, 0x5)
	runtime/panic.go:1117 +0x54 fp=0x140025a9590 sp=0x140025a9560 pc=0x1042c3e44
runtime.sigpanic()`
	`runtime/signal_unix.go:741 +0x230 fp=0x140025a95d0 sp=0x140025a9590 pc=0x1042da5c0
github.com/golang/snappy.encodeBlock(0x1400259c002, 0x12d5, 0x12d5, 0x1400259a000, 0x1007, 0x1c4b, 0x14000719701)
	github.com/golang/snappy@v0.0.2/encode_arm64.s:666 +0x360 fp=0x140025b1670 sp=0x140025a95e0 pc=0x1046aa3d0`
`github.com/golang/snappy.Encode(0x1400259c000, 0x12d7, 0x12d7, 0x0, 0x0, 0x0, 0x14000719798, 0x1046b2710, 0x14000719798)
	github.com/golang/snappy@v0.0.2/encode.go:39 +0x17c fp=0x140025b16c0 sp=0x140025b1670 pc=0x1046a990c
github.com/syndtr/goleveldb/leveldb/table.(*Writer).writeBlock(0x140000a8300, 0x140000a8358, 0x2, 0xffffffffffffffff, 0x3, 0x26, 0x50)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/table/writer.go:170 +0xb0 fp=0x140025b1740 sp=0x140025b16c0 pc=0x1046b2020
github.com/syndtr/goleveldb/leveldb/table.(*Writer).finishBlock(0x140000a8300, 0x14001506138, 0x2f)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/table/writer.go:221 +0x4c fp=0x140025b17a0 sp=0x140025b1740 pc=0x1046b24ec`
`github.com/syndtr/goleveldb/leveldb/table.(*Writer).Append(0x140000a8300, 0x14001506138, 0x2f, 0x3f9ec8, 0x14001506167, 0x2, 0x3f9e99, 0x100, 0x1)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/table/writer.go:254 +0x1e4 fp=0x140025b1810 sp=0x140025b17a0 pc=0x1046b27b4
github.com/syndtr/goleveldb/leveldb.(*tWriter).append(0x140002ad7a0, 0x14001506138, 0x2f, 0x3f9ec8, 0x14001506167, 0x2, 0x3f9e99, 0x0, 0x0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/table.go:490 +0xbc fp=0x140025b1880 sp=0x140025b1810 pc=0x1046d2fec
github.com/syndtr/goleveldb/leveldb.(*tOps).createFrom(0x14000207e00, 0x104d627d8, 0x14000120380, 0x0, 0x0, 0x0, 0x0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/table.go:330 +0x11c fp=0x140025b1920 sp=0x140025b1880 pc=0x1046d22cc
github.com/syndtr/goleveldb/leveldb.(*session).flushMemdb(0x140001fa6e0, 0x140002a00a0, 0x140001ec700, 0x0, 0x0, 0x0, 0x0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/session_compaction.go:27 +0xa4 fp=0x140025b1a70 sp=0x140025b1920 pc=0x1046cb5e4`
github.com/syndtr/goleveldb/leveldb.(*DB).memCompaction.func1(0x140002fe030, 0x104b4a8c0, 0x1400018e301)
	`github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:304 +0x64 fp=0x140025b1af0 sp=0x140025b1a70 pc=0x1046d7fb4
github.com/syndtr/goleveldb/leveldb.(*compactionTransactFunc).run(0x140002fc020, 0x140002fe030, 0x12c6e94a0, 0x1)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:241 +0x34 fp=0x140025b1b20 sp=0x140025b1af0 pc=0x1046bc7f4
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0x1400022eea0, 0x10497f0c3, 0xb, 0x104d54f38, 0x140002fc020)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:185 +0x1cc fp=0x140025b1d50 sp=0x140025b1b20 pc=0x1046bc12c
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransactFunc(...)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:252
github.com/syndtr/goleveldb/leveldb.(*DB).memCompaction(0x1400022eea0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:302 +0x324 fp=0x140025b1f10 sp=0x140025b1d50 pc=0x1046bcdb4`
`github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x1400022eea0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:766 +0x64 fp=0x140025b1fd0 sp=0x140025b1f10 pc=0x1046bfd64`
`runtime.goexit()
	runtime/asm_arm64.s:1130 +0x4 fp=0x140025b1fd0 sp=0x140025b1fd0 pc=0x1042f7284
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x454`

`goroutine 1 [runnable]:
internal/poll.(*FD).writeUnlock(0x1400010ea80)
	internal/poll/fd_mutex.go:248 +0x5c
internal/poll.(*FD).Write(0x1400010ea80, 0x140000acf9a, 0x45, 0x50be, 0x45, 0x0, 0x0)
	internal/poll/fd_unix.go:279 +0x2dc
os.(*File).write(...)
	os/file_posix.go:48
os.(*File).Write(0x14000114048, 0x140000acf9a, 0x45, 0x50be, 0x0, 0x0, 0x0)
	os/file.go:174 +0x60
github.com/syndtr/goleveldb/leveldb.(*iStorageWriter).Write(0x1400252c570, 0x140000acf9a, 0x45, 0x50be, 0x1400253c690, 0x140023da0e0, 0x32)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/storage.go:60 +0x4c
github.com/syndtr/goleveldb/leveldb/journal.(*Writer).writePending(0x140000aa000)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/journal/journal.go:417 +0x84
github.com/syndtr/goleveldb/leveldb/journal.(*Writer).Flush(0x140000aa000, 0x1400253c690, 0x1400071b750)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/journal/journal.go:436 +0x34
github.com/syndtr/goleveldb/leveldb.(*DB).writeJournal(0x1400022eea0, 0x1400071b750, 0x1, 0x1, 0x14702, 0x0, 0x1400071b6e8, 0x1042d5d38)`
	`github.com/syndtr/goleveldb@v1.0.0/leveldb/db_write.go:26 +0x90
github.com/syndtr/goleveldb/leveldb.(*DB).writeLocked(0x1400022eea0, 0x14000046040, 0x14000046040, 0x1, 0x0, 0x0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_write.go:231 +0x334
github.com/syndtr/goleveldb/leveldb.(*DB).putRec(0x1400022eea0, 0x1, 0x14002542ba0, 0x2d, 0x30, 0x140025315b8, 0x2, 0x8, 0x0, 0x14002542b40, ...)`
	`github.com/syndtr/goleveldb@v1.0.0/leveldb/db_write.go:362 +0x220
github.com/syndtr/goleveldb/leveldb.(*DB).Put(...)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_write.go:372
github.com/projectdiscovery/hmap/store/disk.(*LevelDB).set(0x140001326c0, 0x14002542ba0, 0x2d, 0x30, 0x0, 0x0, 0x0, 0x0, 0x1400071bb08, 0x10496c80c)
	github.com/projectdiscovery/hmap@v0.0.1/store/disk/leveldb.go:92 +0x104
github.com/projectdiscovery/hmap/store/disk.(*LevelDB).Set(0x140001326c0, 0x14002542b40, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x140000f5dd0, 0x2d)
	github.com/projectdiscovery/hmap@v0.0.1/store/disk/leveldb.go:97 +0x78
github.com/projectdiscovery/hmap/store/hybrid.(*HybridMap).Set(0x14000046a80, 0x14002542b40, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/projectdiscovery/hmap@v0.0.1/store/hybrid/hybrid.go:122 +0x13c
github.com/projectdiscovery/nuclei/v2/internal/runner.New(0x105260b40, 0x300000002, 0x1400024bf28, 0x104296978)
	github.com/projectdiscovery/nuclei/v2/internal/runner/runner.go:166 +0x4a4
main.main()`
	`command-line-arguments/main.go:23 +0x48`

`goroutine 19 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x140001ec380)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xcc
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x15c`

`goroutine 9 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x1400022f040)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x74
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x30c`

`goroutine 10 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x1400022f040)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x98
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x32c`

`goroutine 11 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x1400022f040)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x18c
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x434`

`goroutine 12 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x1400022f040)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0xd0
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x454`

`goroutine 13 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x140001ec000)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xcc
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x15c`

`goroutine 14 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x1400022e000)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x74
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x30c`

`goroutine 15 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x1400022e000)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x98
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x32c`

`goroutine 16 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x1400022e000)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x18c
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x434`

`goroutine 50 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x1400022e000)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0xd0
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x454`

`goroutine 51 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x140001ec1c0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xcc
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x15c`

`goroutine 52 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x1400022e820)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x74
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x30c`

goroutine 53 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x1400022e820)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x98
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x32c

goroutine 54 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x1400022e820)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x18c
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x434

goroutine 55 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x1400022e820)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0xd0
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x454

goroutine 56 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x140001ec460)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xcc
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x15c

goroutine 57 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x1400022ed00)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x74
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x30c

goroutine 58 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x1400022ed00)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x98
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x32c

goroutine 59 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x1400022ed00)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:825 +0x18c
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x434

goroutine 60 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0x1400022ed00)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:762 +0xd0
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:150 +0x454

goroutine 61 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0x140001ec620)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:206 +0xcc
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	github.com/syndtr/goleveldb@v1.0.0/leveldb/util/buffer_pool.go:237 +0x15c

goroutine 62 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x1400022eea0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:90 +0x74
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:142 +0x30c

goroutine 63 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0x1400022eea0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:101 +0x98
created by github.com/syndtr/goleveldb/leveldb.openDB
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:143 +0x32c

goroutine 64 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).pauseCompaction(0x1400022eea0, 0x1400258a000)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:654 +0x6c
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0x1400022eea0)
	github.com/syndtr/goleveldb@v1.0.0/leveldb/db_compaction.go:828 +0x3b0
created by github.com/syndtr/goleveldb/leveldb.openDB
	`github`.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:149 +0x434`
```

**Comment by Ice3man543** [comment]
@k1000o23 what is the command line you used for running nuclei? Looks like an issue with leveldb on m1.

**Comment by k1000o23** [comment]
@Ice3man543 
> @k1000o23 what is the command line you used for running nuclei? Looks like an issue with leveldb on m1.

the command line:
`nuclei -l subs.txt -t cves/ -o cves_log.txt `

any idea about how to fix this?
