### ISSUE TITLE
[issue] panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by rtcms** [projectdiscovery/nuclei#748]
**Describe the bug**
I was trying to run nuclei with some templates and I get this error

```
panic: assignment to entry in nil map

goroutine 980636 [running]:
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc002034c60, 0xc00302a5a0, 0x19, 0xc004570e10, 0x0, 0xc0039afd08, 0x1, 0x0, 0x0)
	/home/r/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/pkg/protocols/http/request.go:407 +0x1392
github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).ExecuteWithResults(0xc002034c60, 0xc00302a5a0, 0x19, 0xc0039afda0, 0x0, 0xc0020a3240, 0xc0052fd704, 0x2)
	/home/r/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/pkg/protocols/http/request.go:218 +0x28b
github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/clusterer.(*Executer).Execute(0xc00355f320, 0xc00302a5a0, 0x19, 0xc002b93b00, 0xc0052fd748, 0x407295)
	/home/r/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/pkg/protocols/common/clusterer/executer.go:64 +0x119
github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1.1(0xc0020a3000, 0xc00356fba0, 0xc000078000, 0xc00436f718, 0xc00302a5a0, 0x19)
	/home/r/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/internal/runner/processor.go:21 +0x9d
created by github.com/projectdiscovery/nuclei/v2/internal/runner.(*Runner).processTemplateWithList.func1
	/home/r/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.3.7/internal/runner/processor.go:18 +0xfb

```

**Nuclei version**
Please share the version of the nuclei you are running with `nuclei -version` 
`[INF] Current Version: 2.3.7
`

**Screenshot of the error or bug**
![Screenshot from 2021-06-04 00-42-10](https://user-images.githubusercontent.com/35173068/120699211-bd684880-c4cd-11eb-8cb4-397bb436011d.png)

**Comment by ehsandeep** [comment]
@rtcms Can you try this - https://github.com/projectdiscovery/nuclei/issues/745#issuecomment-853566642

**Comment by rtcms** [comment]
I have tried with the `dev` branch and it did work
Thanks for the help closing the issue now :)
