### ISSUE TITLE
invalid memory address [runtime error]

### ISSUE THREAD

**Issue by 1usys** [projectdiscovery/nuclei#998]
```console
nuclei -l targets.txt -t $HOME/nuclei-templates/misconfiguration -c 100 -o nuclei_result.txt

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.5.0

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Using Nuclei Engine 2.5.0 (latest)
[INF] Using Nuclei Templates 8.4.6 (outdated)
[INF] Using Interactsh Server https://interact.sh
[INF] Templates added in last update: 1939
[INF] Templates loaded for scan: 130
[INF] Templates clustered: 14 (Reduced 96756 HTTP Requests)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x6e77bf]

goroutine 6172999 [running]:
crypto/tls.(*Conn).write(0xc002d96380, {0xc002a24480, 0x5, 0xc006368b80})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:912 +0xff
crypto/tls.(*Conn).writeRecordLocked(0xc002d96380, 0x16, {0xc002a85200, 0x10d, 0x180})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:980 +0x351
crypto/tls.(*Conn).writeRecord(0xc002c6ca00, 0x60, {0xc002a85200, 0x1, 0xc005d69448})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1002 +0xe5
crypto/tls.(*Conn).clientHandshake(0xc002d96380, {0x15a41a0, 0xc006d9f080})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/handshake_client.go:175 +0x205
crypto/tls.(*Conn).handshakeContext(0xc002d96380, {0x15a4210, 0xc00668b860})
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1445 +0x3d1
crypto/tls.(*Conn).HandshakeContext(...)
	/opt/hostedtoolcache/go/1.17.0/x64/src/crypto/tls/conn.go:1395
net/http.(*persistConn).addTLS.func2()
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/transport.go:1534 +0x71
created by net/http.(*persistConn).addTLS
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/transport.go:1530 +0x345
```

**Comment by JeffreyShran** [comment]
Also see: https://github.com/projectdiscovery/nuclei/issues/984
